Repository openfisca/openfisca-france, pull requests merged in 2018-04, with the labels that each got.

#949 Prevent incorrect eligibility to cheque energie in Saint Martin
  CHANGELOG.md
  openfisca_france/model/caracteristiques_socio_demographiques/logement.py
  openfisca_france/model/prestations/cheque_energie.py
  setup.py
  tests/formulas/cheque_energie/eligibilite_logement.yaml
Labels: flow:contrib:doing, kind:evolution

#913 Ipp 7 : Update crédit d'IR "qualité environnementale"
  CHANGELOG.md
  openfisca_france/model/prelevements_obligatoires/impot_revenu/credits_impot.py
  openfisca_france/model/prelevements_obligatoires/impot_revenu/reductions_impot.py
  openfisca_france/model/prelevements_obligatoires/impot_revenu/variables_reductions_credits.py
  openfisca_france/parameters/impot_revenu/credits_impot/quaenv/max_rfr.yaml
  openfisca_france/parameters/impot_revenu/credits_impot/quaenv/max_rfr2.yaml
  openfisca_france/parameters/impot_revenu/credits_impot/quaenv/taux25.yaml
  openfisca_france/parameters/impot_revenu/credits_impot/quaenv/taux30.yaml
  setup.py
Labels: contrib:ipp, flow:contrib:backlog, kind:evolution, scope:tax

#961 IPP 9 (bis) : Mise à jour de la réduction d'impôt PME non cotées (2014-2016)
  CHANGELOG.md
  openfisca_france/model/prelevements_obligatoires/impot_revenu/reductions_impot.py
  openfisca_france/model/prelevements_obligatoires/impot_revenu/variables_reductions_credits.py
  setup.py
Labels: flow:contrib:backlog

#916 Ipp 10 : Update et corrige le crédit d'impôt 'aidper'
  CHANGELOG.md
  openfisca_france/model/prelevements_obligatoires/impot_revenu/credits_impot.py
  openfisca_france/model/prelevements_obligatoires/impot_revenu/reductions_impot.py
  openfisca_france/model/prelevements_obligatoires/impot_revenu/variables_reductions_credits.py
  openfisca_france/parameters/impot_revenu/credits_impot/aidper/max_wl.yaml
  setup.py
Labels: flow:contrib:backlog

#917 Ipp 11 : Correction du calcul des revenus non salariaux pour l'IR
  CHANGELOG.md
  openfisca_france/model/prelevements_obligatoires/impot_revenu/credits_impot.py
  openfisca_france/model/prelevements_obligatoires/impot_revenu/ir.py
  openfisca_france/model/prelevements_obligatoires/impot_revenu/reductions_impot.py
  openfisca_france/model/prestations/prestations_familiales/base_ressource.py
  openfisca_france/model/revenus/activite/non_salarie.py
  openfisca_france/parameters/impot_revenu/credits_impot/quaenv/max_rfr.yaml
  openfisca_france/parameters/impot_revenu/rpns/micro/specialbnc/max.yaml
  openfisca_france/parameters/impot_revenu/rpns/micro/specialbnc/min.yaml
  setup.py
Labels: flow:contrib:backlog

#918 Ipp 12 : Update calcul du quotient familial, ajout nouvelle réduction sous conditions de revenus
  CHANGELOG.md
  openfisca_france/model/caracteristiques_socio_demographiques/demographie.py
  openfisca_france/model/prelevements_obligatoires/impot_revenu/credits_impot.py
  openfisca_france/model/prelevements_obligatoires/impot_revenu/ir.py
  openfisca_france/model/prelevements_obligatoires/impot_revenu/reductions_impot.py
  openfisca_france/model/revenus/autres.py
  openfisca_france/parameters/impot_revenu/credits_impot/quaenv/max_rfr.yaml
  openfisca_france/parameters/impot_revenu/plafond_qf/abat_dom/index.yaml
  openfisca_france/parameters/impot_revenu/plafond_qf/abat_dom/plaf_GuadMarReu.yaml
  openfisca_france/parameters/impot_revenu/plafond_qf/abat_dom/plaf_GuyMay.yaml
  openfisca_france/parameters/impot_revenu/plafond_qf/abat_dom/taux_GuadMarReu.yaml
  openfisca_france/parameters/impot_revenu/plafond_qf/abat_dom/taux_GuyMay.yaml
  openfisca_france/parameters/impot_revenu/plafond_qf/celib_E_ou_K.yaml
  openfisca_france/parameters/impot_revenu/plafond_qf/reduc_postplafond_veuf.yaml
  openfisca_france/parameters/impot_revenu/plafond_qf/reduction_ss_condition_revenus/index.yaml
  openfisca_france/parameters/impot_revenu/plafond_qf/reduction_ss_condition_revenus/seuil1.yaml
  openfisca_france/parameters/impot_revenu/plafond_qf/reduction_ss_condition_revenus/seuil2.yaml
  openfisca_france/parameters/impot_revenu/plafond_qf/reduction_ss_condition_revenus/seuil_maj_enf.yaml
  openfisca_france/parameters/impot_revenu/plafond_qf/reduction_ss_condition_revenus/taux.yaml
  openfisca_france/parameters/impot_revenu/quotient_familial/veuf.yaml
  setup.py
Labels: flow:contrib:backlog

#919 Ipp 13 : Update des crédits/réductions d'impôt restants
  CHANGELOG.md
  openfisca_france/model/prelevements_obligatoires/impot_revenu/credits_impot.py
  openfisca_france/model/prelevements_obligatoires/impot_revenu/reductions_impot.py
  openfisca_france/model/prelevements_obligatoires/impot_revenu/variables_reductions_credits.py
  openfisca_france/model/revenus/autres.py
  setup.py
Labels: flow:contrib:backlog

#960 Fix chèque energie implementation
  CHANGELOG.md
  openfisca_france/model/prestations/cheque_energie.py
  setup.py
  tests/formulas/cheque_energie/montant.yaml
  tests/formulas/cheque_energie/unites_consommation.yaml
Labels: contrib:mes-aides, flow:contrib:doing, kind:evolution, scope:social-benefit

#968 Change link to documentation
  CHANGELOG.md
  README.md
  notebooks/getting-started.ipynb
  setup.py
Labels: flow:support:doing, kind:documentation

#962 Améliore template de pull request
  .github/PULL_REQUEST_TEMPLATE.md
  CHANGELOG.md
  setup.py
Labels: flow:team:doing, policy:governance, policy:needs-consensus
