Repository openfisca/openfisca-france, pull requests merged in 2018-08, with the labels that each got.

#1040 Ajoute l'abattement d'IR de 30 ou 40% pour les résidents des DOM
  CHANGELOG.md
  openfisca_france/model/prelevements_obligatoires/impot_revenu/ir.py
  openfisca_france/parameters/impot_revenu/plafond_qf/abat_dom/taux_GuadMarReu.yaml
  openfisca_france/parameters/impot_revenu/plafond_qf/abat_dom/taux_GuyMay.yaml
  setup.py
  tests/impot_revenu/abattement_dom.yaml
Labels: flow:contrib:doing

#992 Revalorisation de la CMUc-ACS au 1er avril 2018
  CHANGELOG.md
  openfisca_france/model/prestations/minima_sociaux/aah.py
  openfisca_france/model/prestations/minima_sociaux/cmu.py
  openfisca_france/model/prestations/minima_sociaux/rsa.py
  openfisca_france/parameters/cmu/plafond_base.yaml
  openfisca_france/parameters/prestations/minima_sociaux/aah/mva.yaml
  setup.py
  tests/formulas/cmu.yaml
  tests/formulas/cmuc_fiab.yaml
  tests/mes-aides.gouv.fr/test_mes_aides_5613ea9691ca94f36e1e3895.yaml
Labels: contrib:msa, flow:contrib:doing

#1065 Ameliore taxation capital + mesures
  CHANGELOG.md
  openfisca_france/france_taxbenefitsystem.py
  openfisca_france/model/mesures.py
  openfisca_france/model/prelevements_obligatoires/impot_revenu/credits_impot.py
  openfisca_france/model/prelevements_obligatoires/impot_revenu/ir.py
  openfisca_france/model/prelevements_obligatoires/impot_revenu/plus_values_immobilieres.py
  openfisca_france/model/prelevements_obligatoires/isf.py
  openfisca_france/model/prelevements_obligatoires/prelevement_forfaitaire_liberatoire.py
  openfisca_france/model/prelevements_obligatoires/prelevements_sociaux/contributions_sociales/capital.py
  openfisca_france/model/prelevements_obligatoires/prelevements_sociaux/contributions_sociales/csg_crds.py
  openfisca_france/model/revenus/capital/financier.py
  openfisca_france/model/revenus/capital/plus_value.py
  openfisca_france/parameters/impot_revenu/rvcm/prelevement_liberatoire/action.yaml
  openfisca_france/parameters/impot_revenu/rvcm/prelevement_liberatoire/assvie.yaml
  openfisca_france/parameters/impot_revenu/rvcm/prelevement_liberatoire/autre.yaml
  openfisca_france/parameters/impot_revenu/rvcm/prelevement_liberatoire/index.yaml
  openfisca_france/parameters/prelevements_sociaux/contributions/csg/capital/deduc.yaml
  openfisca_france/parameters/prelevements_sociaux/contributions/csg/capital/glob.yaml
  openfisca_france/parameters/taxation_capital/pfl.yaml
  openfisca_france/parameters/taxation_capital/pfl_av/bons_ou_contrats_de_capitalisation_et_placements_de_meme_nature_assurance_vie_lors_du_denouement_du_contrat.yaml
  openfisca_france/parameters/taxation_capital/prelevements_sociaux/caps/revenus_du_patrimoine.yaml
  openfisca_france/parameters/taxation_capital/prelevements_sociaux/crds/revenus_du_patrimoine.yaml
  openfisca_france/parameters/taxation_capital/prelevements_sociaux/prelevements_solidarite/revenus_du_patrimoine.yaml
  openfisca_france/reforms/allocations_familiales_imposables.py
  openfisca_france/reforms/cesthra_invalidee.py
  openfisca_france/reforms/landais_piketty_saez.py
  setup.py
  tests/capital/cotisations_sociales_capital.yaml
  tests/capital/prelevement_forfaitaire_liberatoire.yaml
  tests/formulas/irpp.yaml
  tests/formulas/revenu_disponible.yaml
  tests/test_decompositions.py
Labels: contrib:ipp

#1058 Intégration de la réduction de loyer solidarité (RLS) dans la formule de calcul de l’aide personnalisée au logement (APL)
  CHANGELOG.md
  openfisca_france/model/prestations/aides_logement.py
  openfisca_france/parameters/prestations/reduction_loyer_solidarite/fraction_baisse_aide_logement.yaml
  setup.py
  tests/formulas/aides_logement_2018.yaml
  tests/formulas/rls_apl.yaml
Labels: contrib:msa

#1079 Fix taux primes
  CHANGELOG.md
  openfisca_france/model/base.py
  openfisca_france/model/prelevements_obligatoires/impot_revenu/ir.py
  openfisca_france/model/revenus/activite/salarie.py
  setup.py
Labels: flow:contrib:doing

#1075 Code la flat tax (réforme Macron 2018)
  CHANGELOG.md
  openfisca_france/model/mesures.py
  openfisca_france/model/prelevements_obligatoires/impot_revenu/credits_impot.py
  openfisca_france/model/prelevements_obligatoires/impot_revenu/ir.py
  openfisca_france/model/prelevements_obligatoires/impot_revenu/plus_values_immobilieres.py
  openfisca_france/model/prelevements_obligatoires/impot_revenu/prelevements_forfaitaires/__init__.py
  openfisca_france/model/prelevements_obligatoires/impot_revenu/prelevements_forfaitaires/ir_prelevement_forfaitaire_unique.py
  openfisca_france/model/prelevements_obligatoires/impot_revenu/prelevements_forfaitaires/prelevement_forfaitaire_liberatoire.py
  openfisca_france/model/prelevements_obligatoires/impot_revenu/prelevements_forfaitaires/variables_communes.py
  openfisca_france/model/prelevements_obligatoires/isf.py
  openfisca_france/model/prelevements_obligatoires/prelevements_sociaux/contributions_sociales/capital.py
  openfisca_france/model/prestations/aides_logement.py
  openfisca_france/model/prestations/prestations_familiales/base_ressource.py
  openfisca_france/model/revenus/capital/financier.py
  openfisca_france/model/revenus/capital/plus_value.py
  openfisca_france/parameters/impot_revenu/prelevement_forfaitaire_unique_ir/seuil_taux_reduit_av.yaml
  openfisca_france/parameters/impot_revenu/prelevement_forfaitaire_unique_ir/taux.yaml
  openfisca_france/parameters/impot_revenu/prelevement_forfaitaire_unique_ir/taux_reduit_av.yaml
  openfisca_france/reforms/allocations_familiales_imposables.py
  openfisca_france/reforms/landais_piketty_saez.py
  setup.py
  tests/capital/cotisations_sociales_capital.yaml
  tests/capital/prelevement_forfaitaire_liberatoire.yaml
  tests/capital/test_modification_rvcm_bases_ressources_suite_a_prelevement_forfaitaire_unique.yaml
  tests/formulas/irpp_prets_participatifs.yaml
  tests/formulas/revenu_disponible.yaml
Labels: flow:contrib:doing

#1103 Tests de la revalorisation de l'ASPA de 2018-04
  CHANGELOG.md
  setup.py
  tests/formulas/aspa.yaml
Labels: contrib:msa

#1070 Fiabilisation des bases ressources des aides CMU-c et ACS – Intégration de la ressource « Rente d’accident du travail »
  CHANGELOG.md
  openfisca-run-test
  openfisca_france/model/prestations/minima_sociaux/cmu.py
  openfisca_france/model/revenus/remplacement/rente_accident_travail.py
  setup.py
  tests/formulas/cmu_rente_at.yaml
Labels: contrib:msa, flow:contrib:doing
