Repository openfisca/openfisca-france, pull requests merged in 2018-10, with the labels that each got.

#1043 Corrige le calcul de l'ASF
  CHANGELOG.md
  openfisca_france/model/prestations/prestations_familiales/asf.py
  setup.py
  tests/formulas/asf.yaml
  tests/mes-aides.gouv.fr/test_mes_aides_559161a648433cfe2f4370f0.yaml
Labels: flow:qualified-issues-fr

#1135 Linte les fichiers YAML/Python en incrémental
  .circleci/config.yml
  .circleci/lint-changed-python-files.sh
  .circleci/lint-changed-yaml-tests.sh
  CHANGELOG.md
  setup.cfg
  setup.py
Labels: flow:team:doing, kind:improvement

#1137 Suppression du fichier 'openfisca-run-test'
  CHANGELOG.md
  openfisca-run-test
  setup.py
Labels: flow:contrib:doing, kind:improvement

#1138 Application d'un barème spécifique à certains publics "accession" - Aides au logement (FAM_Reforme_Accession)
  CHANGELOG.md
  openfisca_france/model/prestations/aides_logement.py
  setup.cfg
  setup.py
  tests/formulas/aides_logement_accedant_eligibilite.yaml
Labels: contrib:msa

#1139 Lint openfisca_france/model/revenus/**/*
  .circleci/config.yml
  CHANGELOG.md
  Makefile
  openfisca_france/model/revenus/activite/non_salarie.py
  openfisca_france/model/revenus/activite/salarie.py
  openfisca_france/model/revenus/autres.py
  openfisca_france/model/revenus/capital/financier.py
  openfisca_france/model/revenus/capital/plus_value.py
  openfisca_france/model/revenus/remplacement/chomage.py
  openfisca_france/model/revenus/remplacement/indemnites_journalieres_securite_sociale.py
  openfisca_france/model/revenus/remplacement/rente_accident_travail.py
  setup.cfg
  setup.py
Labels: flow:team:doing, kind:improvement

#1143 Linte prelevements_obligatoires
  CHANGELOG.md
  openfisca_france/model/prelevements_obligatoires/impot_revenu/charges_deductibles.py
  openfisca_france/model/prelevements_obligatoires/impot_revenu/credits_impot.py
  openfisca_france/model/prelevements_obligatoires/impot_revenu/ir.py
  openfisca_france/model/prelevements_obligatoires/impot_revenu/plus_values_immobilieres.py
  openfisca_france/model/prelevements_obligatoires/impot_revenu/prelevements_forfaitaires/ir_prelevement_forfaitaire_unique.py
  openfisca_france/model/prelevements_obligatoires/impot_revenu/prelevements_forfaitaires/prelevement_forfaitaire_liberatoire.py
  openfisca_france/model/prelevements_obligatoires/impot_revenu/prelevements_forfaitaires/variables_communes.py
  openfisca_france/model/prelevements_obligatoires/impot_revenu/reductions_impot.py
  openfisca_france/model/prelevements_obligatoires/impot_revenu/variables_reductions_credits.py
  openfisca_france/model/prelevements_obligatoires/isf.py
  openfisca_france/model/prelevements_obligatoires/prelevements_sociaux/contributions_sociales/activite.py
  openfisca_france/model/prelevements_obligatoires/prelevements_sociaux/contributions_sociales/base.py
  openfisca_france/model/prelevements_obligatoires/prelevements_sociaux/contributions_sociales/capital.py
  openfisca_france/model/prelevements_obligatoires/prelevements_sociaux/contributions_sociales/csg_crds.py
  openfisca_france/model/prelevements_obligatoires/prelevements_sociaux/contributions_sociales/remplacement.py
  openfisca_france/model/prelevements_obligatoires/prelevements_sociaux/contributions_sociales/versement_transport.py
  openfisca_france/model/prelevements_obligatoires/prelevements_sociaux/cotisations_sociales/allegements.py
  openfisca_france/model/prelevements_obligatoires/prelevements_sociaux/cotisations_sociales/apprentissage.py
  openfisca_france/model/prelevements_obligatoires/prelevements_sociaux/cotisations_sociales/base.py
  openfisca_france/model/prelevements_obligatoires/prelevements_sociaux/cotisations_sociales/contrat_professionnalisation.py
  openfisca_france/model/prelevements_obligatoires/prelevements_sociaux/cotisations_sociales/exonerations.py
  openfisca_france/model/prelevements_obligatoires/prelevements_sociaux/cotisations_sociales/preprocessing.py
  openfisca_france/model/prelevements_obligatoires/prelevements_sociaux/cotisations_sociales/stage.py
  openfisca_france/model/prelevements_obligatoires/prelevements_sociaux/cotisations_sociales/travail_fonction_publique.py
  openfisca_france/model/prelevements_obligatoires/prelevements_sociaux/cotisations_sociales/travail_non_salarie.py
  openfisca_france/model/prelevements_obligatoires/prelevements_sociaux/cotisations_sociales/travail_prive.py
  openfisca_france/model/prelevements_obligatoires/prelevements_sociaux/cotisations_sociales/travail_totaux.py
  openfisca_france/model/prelevements_obligatoires/prelevements_sociaux/taxes_salaires_main_oeuvre.py
  openfisca_france/model/prelevements_obligatoires/taxe_habitation.py
  setup.cfg
  setup.py
Labels: flow:team:doing, kind:improvement

#1142 Linte prestations
  CHANGELOG.md
  openfisca_france/model/prestations/aides_logement.py
  openfisca_france/model/prestations/anah/eligibilite_anah.py
  openfisca_france/model/prestations/autonomie.py
  openfisca_france/model/prestations/bourses_superieur.py
  openfisca_france/model/prestations/cheque_energie.py
  openfisca_france/model/prestations/education.py
  openfisca_france/model/prestations/logement_social.py
  openfisca_france/model/prestations/minima_sociaux/aah.py
  openfisca_france/model/prestations/minima_sociaux/ada.py
  openfisca_france/model/prestations/minima_sociaux/aefa.py
  openfisca_france/model/prestations/minima_sociaux/anciens_ms.py
  openfisca_france/model/prestations/minima_sociaux/asi_aspa.py
  openfisca_france/model/prestations/minima_sociaux/ass.py
  openfisca_france/model/prestations/minima_sociaux/cmu.py
  openfisca_france/model/prestations/minima_sociaux/ppa.py
  openfisca_france/model/prestations/minima_sociaux/rsa.py
  openfisca_france/model/prestations/prestations_familiales/aeeh.py
  openfisca_france/model/prestations/prestations_familiales/af.py
  openfisca_france/model/prestations/prestations_familiales/ars.py
  openfisca_france/model/prestations/prestations_familiales/asf.py
  openfisca_france/model/prestations/prestations_familiales/base_ressource.py
  openfisca_france/model/prestations/prestations_familiales/cf.py
  openfisca_france/model/prestations/prestations_familiales/paje.py
  openfisca_france/model/prestations/reduction_loyer_solidarite.py
  openfisca_france/model/revenus/activite/non_salarie.py
  openfisca_france/model/revenus/activite/salarie.py
  openfisca_france/model/revenus/autres.py
  openfisca_france/model/revenus/capital/financier.py
  openfisca_france/model/revenus/capital/foncier.py
  openfisca_france/model/revenus/capital/plus_value.py
  openfisca_france/model/revenus/remplacement/chomage.py
  openfisca_france/model/revenus/remplacement/indemnites_journalieres_securite_sociale.py
  openfisca_france/model/revenus/remplacement/rente_accident_travail.py
  openfisca_france/model/revenus/remplacement/retraite.py
  setup.py
Labels: flow:team:doing, kind:improvement

#1144 Linte model
  CHANGELOG.md
  openfisca_france/model/base.py
  openfisca_france/model/caracteristiques_socio_demographiques/demographie.py
  openfisca_france/model/caracteristiques_socio_demographiques/logement.py
  openfisca_france/model/mesures.py
  setup.py
Labels: kind:improvement, level:starter

#1145 Linte model/prelevements (W504)
  CHANGELOG.md
  openfisca_france/model/prelevements_obligatoires/impot_revenu/charges_deductibles.py
  openfisca_france/model/prelevements_obligatoires/impot_revenu/credits_impot.py
  openfisca_france/model/prelevements_obligatoires/impot_revenu/ir.py
  openfisca_france/model/prelevements_obligatoires/impot_revenu/reductions_impot.py
  openfisca_france/model/prelevements_obligatoires/isf.py
  openfisca_france/model/prelevements_obligatoires/prelevements_sociaux/contributions_sociales/activite.py
  openfisca_france/model/prelevements_obligatoires/prelevements_sociaux/contributions_sociales/capital.py
  openfisca_france/model/prelevements_obligatoires/prelevements_sociaux/contributions_sociales/remplacement.py
  openfisca_france/model/prelevements_obligatoires/prelevements_sociaux/cotisations_sociales/allegements.py
  openfisca_france/model/prelevements_obligatoires/prelevements_sociaux/cotisations_sociales/apprentissage.py
  openfisca_france/model/prelevements_obligatoires/prelevements_sociaux/cotisations_sociales/exonerations.py
  openfisca_france/model/prelevements_obligatoires/prelevements_sociaux/cotisations_sociales/travail_fonction_publique.py
  openfisca_france/model/prelevements_obligatoires/prelevements_sociaux/cotisations_sociales/travail_prive.py
  openfisca_france/model/prelevements_obligatoires/prelevements_sociaux/cotisations_sociales/travail_totaux.py
  openfisca_france/model/prelevements_obligatoires/prelevements_sociaux/taxes_salaires_main_oeuvre.py
  setup.py
Labels: flow:team:doing, kind:improvement, level:intermediate

#1146 Linte model/prestations (W504)
  CHANGELOG.md
  openfisca_france/model/prestations/aides_logement.py
  openfisca_france/model/prestations/autonomie.py
  openfisca_france/model/prestations/education.py
  openfisca_france/model/prestations/minima_sociaux/aah.py
  openfisca_france/model/prestations/minima_sociaux/aefa.py
  openfisca_france/model/prestations/minima_sociaux/asi_aspa.py
  openfisca_france/model/prestations/minima_sociaux/ppa.py
  openfisca_france/model/prestations/prestations_familiales/af.py
  setup.py
Labels: flow:team:doing, kind:improvement, level:intermediate

#1147 Linte model/revenus (W504)
  CHANGELOG.md
  openfisca_france/model/revenus/activite/non_salarie.py
  openfisca_france/model/revenus/activite/salarie.py
  setup.py
Labels: flow:team:doing, kind:improvement, level:intermediate

#1153 Lint openfisca_france
  CHANGELOG.md
  openfisca_france/assets/holidays.py
  openfisca_france/conf/cache_blacklist.py
  openfisca_france/france_taxbenefitsystem.py
  openfisca_france/reforms/allocations_familiales_imposables.py
  openfisca_france/reforms/cesthra_invalidee.py
  openfisca_france/reforms/de_net_a_brut.py
  openfisca_france/reforms/inversion_directe_salaires.py
  openfisca_france/reforms/inversion_revenus.py
  openfisca_france/reforms/landais_piketty_saez.py
  openfisca_france/reforms/plf2015.py
  openfisca_france/reforms/plf2016.py
  openfisca_france/reforms/plf2016_ayrault_muet.py
  openfisca_france/reforms/plfr2014.py
  openfisca_france/reforms/simulation_reform.py
  openfisca_france/reforms/smic_h_b_9_euros.py
  openfisca_france/reforms/trannoy_wasmer.py
  openfisca_france/scenarios.py
  openfisca_france/scripts/cnaf/exploitation_rsa.py
  openfisca_france/scripts/cnaf/formulaires_caf.py
  openfisca_france/scripts/cnaf/get_tree.py
  openfisca_france/scripts/cnaf/simul_logement.py
  openfisca_france/scripts/cnaf/simul_rsa.py
  openfisca_france/scripts/date_variables.py
  openfisca_france/scripts/dates_variables.json
  openfisca_france/scripts/download_mes_aides_tests.py
  openfisca_france/scripts/inspect_dgfip_variable.py
  openfisca_france/scripts/measure_performances.py
  openfisca_france/scripts/migrations/xml_to_yaml_france.py
  openfisca_france/scripts/parameters/baremes_ipp/README.md
  openfisca_france/scripts/parameters/baremes_ipp/merge_ipp_xml_files_with_openfisca_parameters.py
  openfisca_france/scripts/parameters/baremes_ipp/transform_ipp_tree.py
  openfisca_france/scripts/parameters/baremes_ipp/xls_to_yaml_raw.py
  openfisca_france/scripts/parameters/baremes_ipp/yaml_clean_to_xml.py
  openfisca_france/scripts/parameters/baremes_ipp/yaml_raw_to_yaml_clean.py
  openfisca_france/scripts/parameters/explore_parameters_unit.py
  openfisca_france/scripts/performance_tests/test_circleci_builds.py
  openfisca_france/scripts/performance_tests/test_tests.py
  openfisca_france/scripts/rattachement.py
  openfisca_france/scripts/web_trace.py
  setup.py
Labels: flow:team:reviewing, kind:improvement

#1155 Supprime et corrige scripts
  CHANGELOG.md
  openfisca_france/scripts/calculate_all_columns.py
  openfisca_france/scripts/cnaf/exploitation_rsa.py
  openfisca_france/scripts/cnaf/formulaires_caf.py
  openfisca_france/scripts/cnaf/get_tree.py
  openfisca_france/scripts/cnaf/simul_logement.py
  openfisca_france/scripts/cnaf/simul_rsa.py
  openfisca_france/scripts/date_variables.py
  openfisca_france/scripts/dates_variables.json
  openfisca_france/scripts/download_mes_aides_tests.py
  openfisca_france/scripts/holidays_generator.py
  openfisca_france/scripts/inspect_dgfip_variable.py
  openfisca_france/scripts/parameters/explore_parameters_unit.py
  openfisca_france/scripts/performance/__init__.py
  openfisca_france/scripts/performance/measure_calculations_performance.py
  openfisca_france/scripts/performance/measure_circleci_builds_diff.py
  openfisca_france/scripts/performance/measure_tests_performance.py
  openfisca_france/scripts/rattachement.py
  openfisca_france/scripts/web_trace.py
  setup.py
Labels: flow:qualified-issues-fr, kind:improvement

#1151 Met à jour les tests sur la décote 2013
  CHANGELOG.md
  setup.py
  tests/formulas/irpp.yaml
Labels: flow:qualified-issues-fr

#1149 Factorise la duplication dans le calcul de la 'Prime de Noël'
  CHANGELOG.md
  openfisca_france/model/prestations/minima_sociaux/aefa.py
  openfisca_france/parameters/prestations/minima_sociaux/aefa/forf2008.yaml
  openfisca_france/parameters/prestations/minima_sociaux/aefa/mon_seul.yaml
  openfisca_france/parameters/prestations/minima_sociaux/aefa/prime_exceptionnelle.yaml
  setup.py
Labels: flow:qualified-issues-fr

#1150 Supprime la variable allocation_aide_retour_emploi
  CHANGELOG.md
  openfisca_france/model/prestations/minima_sociaux/cmu.py
  openfisca_france/model/prestations/minima_sociaux/rsa.py
  openfisca_france/model/revenus/autres.py
  setup.py
Labels: flow:qualified-issues-fr

#1173 Linte la totale
  CHANGELOG.md
  Makefile
  README.md
  openfisca_france/model/prestations/minima_sociaux/aah.py
  setup.py
  tests/reforms/test_allocations_familliales_imposables.py
  tests/reforms/test_parametric_reform.py
  tests/reforms/test_plf2016.py
  tests/reforms/test_plf2016_ayrault_muet.py
  tests/reforms/test_plfr2014.py
  tests/test_api.py
  tests/test_coefficient.py
  tests/test_entities.py
  tests/test_nb_enfants.py
  tests/test_parameters.py
  tests/test_tax_rates.py
  tests/utils.py
Labels: flow:contrib:doing, kind:improvement

#1152 Mise à jour du taux de versement transport
  CHANGELOG.md
  openfisca_france/assets/versement_transport/taux.json
  setup.py
Labels: flow:qualified-issues-fr

#1171 Revalorisation du complément familial (CF) au 1er avril 2018
  CHANGELOG.md
  setup.py
  tests/formulas/cf_2018_04.yaml
Labels: contrib:msa

#1184 Revalorisation des allocations familiales, de la majoration pour âge et du forfait d'AF au 1er avril 2018
  CHANGELOG.md
  setup.py
  tests/formulas/af_2018_01.yaml
  tests/formulas/af_2018_04.yaml
Labels: contrib:msa

#1194 Revalorisation du montant de l'Allocation de soutien Familial (ASF) au 1er avril 2018
  CHANGELOG.md
  openfisca_france/parameters/prestations/prestations_familiales/asf/taux_1_parent.yaml
  openfisca_france/parameters/prestations/prestations_familiales/asf/taux_2_parents.yaml
  setup.py
  tests/formulas/asf.yaml
  tests/formulas/asf_2015_01.yaml
  tests/formulas/asf_2018_04.yaml
Labels: contrib:msa

#1178 Teste contre la version build
  .circleci/config.yml
  .circleci/has-functional-changes.sh
  .circleci/publish-python-package.sh
  CHANGELOG.md
  MANIFEST.in
  Makefile
  openfisca_france/assets/apl/extract_subcommunes.py
  openfisca_france/scripts/parameters/baremes_ipp/merge_ipp_xml_files_with_openfisca_parameters.py
  openfisca_france/scripts/parameters/explore_parameters_unit.py
  openfisca_france/scripts/parameters/reduce_parameters_paths.py
  openfisca_france/scripts/performance/measure_calculations_performance.py
  openfisca_france/scripts/performance/measure_tests_performance.py
  setup.py
  tests/test_basics.py
  tests/test_decomposition_fiches_de_paie.py
Labels: flow:team:reviewing, kind:improvement

#1180 Utilise PyTest
  .circleci/config.yml
  CHANGELOG.md
  Makefile
  README.md
  setup.cfg
  setup.py
  tests/reforms/test_plf2015.py
  tests/reforms/test_plf2016.py
  tests/test_coefficient.py
  tests/test_metadata.py
  tests/test_repairs.py
  tests/test_suggestions.py
  tests/utils.py
Labels: flow:team:doing, kind:improvement
