Repository openfisca/openfisca-france, pull requests merged in 2018-09, with the labels that each got.

#1112 Check version and changelog separately
  .circleci/config.yml
Labels: flow:contrib:doing, kind:devops

#1098 Msa fiabilisation rsa
  CHANGELOG.md
  openfisca_france/model/prestations/minima_sociaux/rsa.py
  openfisca_france/parameters/prestations/minima_sociaux/rsa/age_max_rsa_jeune.yaml
  openfisca_france/parameters/prestations/minima_sociaux/rsa/age_min_rsa_jeune.yaml
  openfisca_france/parameters/prestations/minima_sociaux/rsa/rsa_jeune.yaml
  openfisca_france/parameters/prestations/prestations_familiales/af/bmaf.yaml
  setup.py
  tests/formulas/rsa.yaml
  tests/formulas/rsa/rsa_2017.yaml
Labels: contrib:msa, flow:qualified-issues-fr

#1132 Efface __init.py__ de la racine
  CHANGELOG.md
  __init__.py
  setup.py
Labels: flow:team:doing, kind:improvement, note:developer-experience

#1114 Déroule séparément les tests statiques (linting)
  .circleci/config.yml
Labels: flow:contrib:doing, kind:improvement

#1134 Fiabilisation de la Prime d’activité (PPA) au 1er avril 2018
  CHANGELOG.md
  openfisca_france/model/prestations/minima_sociaux/ppa.py
  setup.py
  tests/formulas/ppa_2018.yaml
Labels: contrib:msa
