Repository openfisca/openfisca-france, pull requests merged in 2018-06, with the labels that each got.

#993 Revalorisation de l'AAH au 1er avril 2018
  CHANGELOG.md
  openfisca_france/parameters/prestations/minima_sociaux/aah/montant.yaml
  openfisca_france/parameters/prestations/minima_sociaux/caah/garantie_ressources.yaml
  setup.py
  tests/formulas/aah.yaml
Labels: flow:contrib:backlog

#1007 Rename script and actually deploy in Python 3
  .circleci/config.yml
  .circleci/has-functional-changes.sh
Labels: flow:team:doing, kind:bug

#986 Intégration des nouvelles règles de l'intéressement - Allocation de Solidarité Spécifique
  CHANGELOG.md
  openfisca_france/model/prestations/minima_sociaux/ass.py
  setup.py
  tests/formulas/ass_interessement.yaml
Labels: contrib:msa, flow:contrib:backlog

#1011 Corrige les liens dans le texte d'accompagnement des PRs
  .github/PULL_REQUEST_TEMPLATE.md
Labels: flow:team:doing, kind:documentation

#1012 Compare les peformances d'un commit à celles de la branch Master
  CHANGELOG.md
  __init__.py
  openfisca_france/scripts/performance_tests/test_circleci_builds.py
  setup.py
Labels: flow:team:doing, kind:investigation, note:developer-experience, note:performance

#1017 Update divers paramètres de l'IR pour les périodes récentes (2015-2017)
  CHANGELOG.md
  openfisca_france/parameters/impot_revenu/abattements_rni/enfant_marie/montant.yaml
  openfisca_france/parameters/impot_revenu/abattements_rni/personne_agee_ou_invalide/montant.yaml
  openfisca_france/parameters/impot_revenu/abattements_rni/personne_agee_ou_invalide/plafond_de_ressources_1.yaml
  openfisca_france/parameters/impot_revenu/abattements_rni/personne_agee_ou_invalide/plafond_de_ressources_2.yaml
  openfisca_france/parameters/impot_revenu/charges_deductibles/pensions_alimentaires/plafond.yaml
  openfisca_france/parameters/impot_revenu/charges_deductibles/versements_perp/max.yaml
  openfisca_france/parameters/impot_revenu/charges_deductibles/versements_perp/min.yaml
  openfisca_france/parameters/impot_revenu/decote/seuil_celib.yaml
  openfisca_france/parameters/impot_revenu/decote/seuil_couple.yaml
  openfisca_france/parameters/impot_revenu/exo_ir/conditions_de_ressources_pour_exoneration_d_ir/apprentis.yaml
  openfisca_france/parameters/impot_revenu/exo_ir/conditions_de_ressources_pour_exoneration_d_ir/moins_de_65_ans_4.yaml
  openfisca_france/parameters/impot_revenu/exo_ir/conditions_de_ressources_pour_exoneration_d_ir/plus_de_65_ans_4.yaml
  openfisca_france/parameters/impot_revenu/plafond_qf/celib.yaml
  openfisca_france/parameters/impot_revenu/plafond_qf/celib_enf.yaml
  openfisca_france/parameters/impot_revenu/plafond_qf/decote/seuil1.yaml
  openfisca_france/parameters/impot_revenu/plafond_qf/decote/seuil2.yaml
  openfisca_france/parameters/impot_revenu/plafond_qf/general.yaml
  openfisca_france/parameters/impot_revenu/plafond_qf/reduc_postplafond.yaml
  openfisca_france/parameters/impot_revenu/plafond_qf/reduc_postplafond_veuf.yaml
  openfisca_france/parameters/impot_revenu/plafond_qf/reduction_ss_condition_revenus/seuil1.yaml
  openfisca_france/parameters/impot_revenu/plafond_qf/reduction_ss_condition_revenus/seuil2.yaml
  openfisca_france/parameters/impot_revenu/plafond_qf/reduction_ss_condition_revenus/seuil_maj_enf.yaml
  openfisca_france/parameters/impot_revenu/plafond_qf/veuf.yaml
  openfisca_france/parameters/impot_revenu/reductions_impots/donapd/max.yaml
  openfisca_france/parameters/impot_revenu/reductions_impots/dons/dons_coluche/plafond.yaml
  openfisca_france/parameters/impot_revenu/rpns/micro/imputation_sur_le_revenu_global/plafond_deficits_agricoles.yaml
  openfisca_france/parameters/impot_revenu/rpns/micro/specialbnc/marchandises/max.yaml
  openfisca_france/parameters/impot_revenu/rpns/micro/specialbnc/services/max.yaml
  openfisca_france/parameters/impot_revenu/rpns/micro/specialbnc/services/taux.yaml
  openfisca_france/parameters/impot_revenu/tspr/abatpen/max.yaml
  openfisca_france/parameters/impot_revenu/tspr/abatpen/min.yaml
  openfisca_france/parameters/impot_revenu/tspr/abatpro/max.yaml
  openfisca_france/parameters/impot_revenu/tspr/abatpro/min.yaml
  openfisca_france/parameters/impot_revenu/tspr/abatpro/min2.yaml
  setup.py
Labels: flow:contrib:doing
