Repository openfisca/openfisca-france, pull requests merged in 2018-11, with the labels that each got.

#1183 Précise pourquoi on exclut l'AAH de la base ressources ASPA
  CHANGELOG.md
  openfisca_france/model/prestations/minima_sociaux/asi_aspa.py
  setup.py
Labels: flow:qualified-issues-fr, kind:documentation, level:starter

#1154 Déprécier extra_params
  CHANGELOG.md
  openfisca_france/model/prestations/minima_sociaux/ppa.py
  openfisca_france/model/prestations/minima_sociaux/rsa.py
  setup.py
Labels: flow:qualified-issues-fr, level:starter

#1195 Unifie les formules datées des réductions d'impôt
  CHANGELOG.md
  openfisca_france/model/prelevements_obligatoires/impot_revenu/reductions_impot.py
  setup.py
Labels: flow:team:reviewing

#1200 Corrige le calcul des aides au logement
  CHANGELOG.md
  openfisca_france/model/mesures.py
  setup.py
  tests/formulas/aides_logement_2018.yaml
Labels: flow:team:reviewing

#1209 Améliore la gestion des crédits d'impôt sur valeurs étrangères
  CHANGELOG.md
  openfisca_france/model/prelevements_obligatoires/impot_revenu/ir.py
  openfisca_france/model/prelevements_obligatoires/prelevements_sociaux/contributions_sociales/capital.py
  openfisca_france/model/revenus/capital/financier.py
  setup.py
Labels: flow:team:reviewing

#1218 Update doc links
  .circleci/has-functional-changes.sh
  CHANGELOG.md
  CONTRIBUTING.md
  README.md
  openfisca_france/scripts/parameters/baremes_ipp/README.md
Labels: flow:team:reviewing

#1199 Revalorisation des barèmes spécifiques à certains publics "logements foyers" - Aides au logement (FAM_Reforme_Logements Foyers)
  CHANGELOG.md
  openfisca_france/conf/cache_blacklist.py
  openfisca_france/model/caracteristiques_socio_demographiques/logement.py
  openfisca_france/model/prestations/aides_logement.py
  openfisca_france/parameters/prestations/aides_logement/al_min/montant_min_mensuel/montant_min_apl_al.yaml
  openfisca_france/parameters/prestations/aides_logement/autres/abattement_forfaitaire.yaml
  openfisca_france/parameters/prestations/aides_logement/ressources/dar_11.yaml
  openfisca_france/parameters/prestations/aides_logement/ressources/dar_12.yaml
  openfisca_france/parameters/prestations/aides_logement/ressources/dar_3.yaml
  openfisca_france/parameters/prestations/al_param/parametre_n/al/1_personne_a_charge.yaml
  openfisca_france/parameters/prestations/al_param/parametre_n/al/2_personnes_a_charge.yaml
  openfisca_france/parameters/prestations/al_param/parametre_n/al/3_personnes_a_charge.yaml
  openfisca_france/parameters/prestations/al_param/parametre_n/al/4_personnes_a_charge.yaml
  openfisca_france/parameters/prestations/al_param/parametre_n/al/index.yaml
  openfisca_france/parameters/prestations/al_param/parametre_n/al/isole_0_personne_a_charge.yaml
  openfisca_france/parameters/prestations/al_param/parametre_n/al/majoration_n_par_personne_a_charge_supplementaire.yaml
  openfisca_france/parameters/prestations/al_param/parametre_n/al/menage_0_personnes_a_charge.yaml
  openfisca_france/parameters/prestations/al_param/parametre_n/apl/1_personne_a_charge.yaml
  openfisca_france/parameters/prestations/al_param/parametre_n/apl/2_personnes_a_charge.yaml
  openfisca_france/parameters/prestations/al_param/parametre_n/apl/3_personnes_a_charge.yaml
  openfisca_france/parameters/prestations/al_param/parametre_n/apl/4_personnes_a_charge.yaml
  openfisca_france/parameters/prestations/al_param/parametre_n/apl/index.yaml
  openfisca_france/parameters/prestations/al_param/parametre_n/apl/isole_0_personne_a_charge.yaml
  openfisca_france/parameters/prestations/al_param/parametre_n/apl/majoration_n_par_personne_a_charge_supplementaire.yaml
  openfisca_france/parameters/prestations/al_param/parametre_n/apl/menage_0_personnes_a_charge.yaml
  openfisca_france/parameters/prestations/al_param_accal/bareme_loyer_minimum_lo.yaml
  openfisca_france/parameters/prestations/al_param_accal/bareme_loyer_minimum_lo_apl1.yaml
  openfisca_france/parameters/prestations/al_param_accal/constante_du_coefficient_k.yaml
  openfisca_france/parameters/prestations/al_param_accal/constante_du_coefficient_k_apl1.yaml
  openfisca_france/parameters/prestations/al_param_accal/majoration_du_loyer_minimum_lo_apl1.yaml
  openfisca_france/parameters/prestations/al_param_accal/multiplicateur_de_n.yaml
  openfisca_france/parameters/prestations/al_param_accal/n_0_personnes_a_charge/index.yaml
  openfisca_france/parameters/prestations/al_param_accal/n_0_personnes_a_charge/isole.yaml
  openfisca_france/parameters/prestations/al_param_accal/n_0_personnes_a_charge/menage.yaml
  openfisca_france/parameters/prestations/al_param_accapl/n_0_personnes_a_charge/index.yaml
  openfisca_france/parameters/prestations/al_param_accapl/n_0_personnes_a_charge/isole.yaml
  openfisca_france/parameters/prestations/al_param_accapl/n_0_personnes_a_charge/menage.yaml
  openfisca_france/parameters/prestations/al_plafonds_logement_foyer/conventionne/zone_1.yaml
  openfisca_france/parameters/prestations/al_plafonds_logement_foyer/conventionne/zone_2.yaml
  openfisca_france/parameters/prestations/al_plafonds_logement_foyer/conventionne/zone_3.yaml
  openfisca_france/parameters/prestations/al_plafonds_logement_foyer/personne_agee/couple.yaml
  openfisca_france/parameters/prestations/al_plafonds_logement_foyer/personne_agee/personne_isolee.yaml
  openfisca_france/parameters/prestations/al_plafonds_logement_foyer_crous/non_rehabilitee/couple.yaml
  openfisca_france/parameters/prestations/al_plafonds_logement_foyer_crous/non_rehabilitee/personne_isolee.yaml
  openfisca_france/parameters/prestations/al_plafonds_logement_foyer_crous/rehabilitee/couple.yaml
  openfisca_france/parameters/prestations/al_plafonds_logement_foyer_crous/rehabilitee/personne_isolee.yaml
  setup.py
  tests/formulas/aides_logement.yaml
  tests/formulas/aides_logement_accedant_eligibilite.yaml
  tests/formulas/aides_logement_foyer.yaml
  tests/formulas/aides_logement_primo_accedant.yaml
  tests/mes-aides.gouv.fr/500E_mois_APL_Zone_1.yaml
  tests/mes-aides.gouv.fr/500E_mois_APL_Zone_2.yaml
  tests/mes-aides.gouv.fr/500E_mois_APL_Zone_3.yaml
  tests/mes-aides.gouv.fr/aides_logement_primo_accedant_dhup.yaml
  tests/mes-aides.gouv.fr/testMAcas1_6_couple_accedant_a_la_propriete_AL_1126_E_M_de_salaire_net.yaml
Labels: contrib:msa, flow:team:reviewing

#1207 Améliore les mesures économiques
  CHANGELOG.md
  openfisca_france/model/mesures.py
  openfisca_france/model/prelevements_obligatoires/prelevements_sociaux/contributions_sociales/csg_crds.py
  setup.py
  tests/formulas/prelevements_sociaux_menage.yaml
  tests/formulas/revenus_super_bruts_menage.yaml
  tests/reforms/test_plf2016.py
  tests/reforms/test_plf2016_ayrault_muet.py
  tests/reforms/test_plfr2014.py
Labels: flow:team:reviewing

#1221 Corrige la cotisation exceptionnelle de solidarité
  CHANGELOG.md
  openfisca_france/model/prelevements_obligatoires/prelevements_sociaux/cotisations_sociales/travail_fonction_publique.py
  openfisca_france/model/prelevements_obligatoires/prelevements_sociaux/cotisations_sociales/travail_prive.py
  openfisca_france/model/revenus/activite/salarie.py
  setup.py
Labels: flow:team:reviewing

#1219 Fix fonction publique
  CHANGELOG.md
  openfisca_france/model/prelevements_obligatoires/prelevements_sociaux/contributions_sociales/remplacement.py
  openfisca_france/model/prelevements_obligatoires/prelevements_sociaux/cotisations_sociales/travail_totaux.py
  openfisca_france/model/revenus/activite/salarie.py
  setup.py
Labels: flow:team:reviewing

#1223 Privilégie la notion de logement conventionné pour la détermination du secteur APL
  CHANGELOG.md
  openfisca_france/model/prestations/aides_logement.py
  setup.py
  tests/formulas/aides_logement_2018.yaml
  tests/formulas/aides_logement_foyer.yaml
  tests/formulas/rls_apl.yaml
Labels: contrib:msa, flow:team:reviewing

#1217 Prise en compte de la RLS dans le calcul des prestations sociales
  CHANGELOG.md
  openfisca_france/model/mesures.py
  openfisca_france/model/prestations/aides_logement.py
  openfisca_france/model/prestations/reduction_loyer_solidarite.py
  setup.py
  tests/formulas/revenu_disponible.yaml
  tests/formulas/rls.yaml
Labels: flow:team:reviewing
