Repository openfisca/openfisca-france, pull requests merged in 2018-05, with the labels that each got.

#982 Cleanup old enums
  CHANGELOG.md
  CONTRIBUTING.md
  openfisca_france/model/base.py
  openfisca_france/model/prelevements_obligatoires/impot_revenu/charges_deductibles.py
  openfisca_france/model/prelevements_obligatoires/impot_revenu/variables_reductions_credits.py
  openfisca_france/model/prelevements_obligatoires/prelevements_sociaux/contributions_sociales/activite.py
  openfisca_france/model/prelevements_obligatoires/prelevements_sociaux/contributions_sociales/remplacement.py
  openfisca_france/model/revenus/activite/non_salarie.py
  openfisca_france/model/revenus/activite/salarie.py
  openfisca_france/model/revenus/autres.py
  openfisca_france/model/revenus/capital/plus_value.py
  openfisca_france/model/revenus/remplacement/chomage.py
  setup.py
Labels: flow:team:doing, kind:improvement

#977 Revalorisation de l'ASS au 1er avril 2018
  CHANGELOG.md
  openfisca_france/parameters/prestations/minima_sociaux/ass/montant_plein.yaml
  setup.py
  tests/formulas/ass_04_2018.yaml
Labels: contrib:msa

#984 Revalorisation de la PPA au 1er avril 2018
  CHANGELOG.md
  openfisca_france/parameters/prestations/minima_sociaux/ppa/montant_de_base.yaml
  setup.py
  tests/formulas/ppa_2018.yaml
Labels: contrib:msa, flow:contrib:backlog

#985 Revalorisation du RSA au 1er avril 2018
  CHANGELOG.md
  openfisca_france/parameters/prestations/minima_sociaux/rsa/montant_de_base_du_rsa.yaml
  setup.py
Labels: contrib:msa, flow:contrib:backlog

#983 Revalorisation de l'AL au 1er janvier 2018
  CHANGELOG.md
  openfisca_france/parameters/prestations/aides_logement/ressources/dar_4.yaml
  openfisca_france/parameters/prestations/aides_logement/ressources/dar_8.yaml
  openfisca_france/parameters/prestations/aides_logement/ressources/dar_9.yaml
  setup.py
Labels: contrib:msa, flow:contrib:backlog
