Repository openfisca/openfisca-france, pull requests merged in 2018-07, with the labels that each got.

#1008 Logement social
  CHANGELOG.md
  openfisca_france/model/prestations/logement_social.py
  openfisca_france/parameters/logement_social/plai/plafond_ressources/par_categorie_de_menage/categorie_1/autres_regions.yaml
  openfisca_france/parameters/logement_social/plai/plafond_ressources/par_categorie_de_menage/categorie_1/ile_de_france.yaml
  openfisca_france/parameters/logement_social/plai/plafond_ressources/par_categorie_de_menage/categorie_1/paris_communes_limitrophes.yaml
  openfisca_france/parameters/logement_social/plai/plafond_ressources/par_categorie_de_menage/categorie_2/autres_regions.yaml
  openfisca_france/parameters/logement_social/plai/plafond_ressources/par_categorie_de_menage/categorie_2/ile_de_france.yaml
  openfisca_france/parameters/logement_social/plai/plafond_ressources/par_categorie_de_menage/categorie_2/paris_communes_limitrophes.yaml
  openfisca_france/parameters/logement_social/plai/plafond_ressources/par_categorie_de_menage/categorie_3/autres_regions.yaml
  openfisca_france/parameters/logement_social/plai/plafond_ressources/par_categorie_de_menage/categorie_3/ile_de_france.yaml
  openfisca_france/parameters/logement_social/plai/plafond_ressources/par_categorie_de_menage/categorie_3/paris_communes_limitrophes.yaml
  openfisca_france/parameters/logement_social/plai/plafond_ressources/par_categorie_de_menage/categorie_4/autres_regions.yaml
  openfisca_france/parameters/logement_social/plai/plafond_ressources/par_categorie_de_menage/categorie_4/ile_de_france.yaml
  openfisca_france/parameters/logement_social/plai/plafond_ressources/par_categorie_de_menage/categorie_4/paris_communes_limitrophes.yaml
  openfisca_france/parameters/logement_social/plai/plafond_ressources/par_categorie_de_menage/categorie_5/autres_regions.yaml
  openfisca_france/parameters/logement_social/plai/plafond_ressources/par_categorie_de_menage/categorie_5/ile_de_france.yaml
  openfisca_france/parameters/logement_social/plai/plafond_ressources/par_categorie_de_menage/categorie_5/paris_communes_limitrophes.yaml
  openfisca_france/parameters/logement_social/plai/plafond_ressources/par_categorie_de_menage/categorie_6/autres_regions.yaml
  openfisca_france/parameters/logement_social/plai/plafond_ressources/par_categorie_de_menage/categorie_6/ile_de_france.yaml
  openfisca_france/parameters/logement_social/plai/plafond_ressources/par_categorie_de_menage/categorie_6/paris_communes_limitrophes.yaml
  openfisca_france/parameters/logement_social/plai/plafond_ressources/par_personne_supplementaire/autres_regions.yaml
  openfisca_france/parameters/logement_social/plai/plafond_ressources/par_personne_supplementaire/ile_de_france.yaml
  openfisca_france/parameters/logement_social/plai/plafond_ressources/par_personne_supplementaire/paris_communes_limitrophes.yaml
  setup.py
  tests/formulas/logement_social_categorie_menage.yaml
  tests/formulas/logement_social_eligible.yaml
  tests/formulas/logement_social_plafonds_ressources.yaml
  tests/formulas/logement_social_zone.yaml
Labels: flow:contrib:doing

#1030 Fix logement social in Corse
  CHANGELOG.md
  openfisca_france/model/prestations/logement_social.py
  setup.py
  tests/formulas/logement_social_zone.yaml
Labels: flow:contrib:doing

#1032 Fix du script qui détermine le besoin d'un bump de version
  .circleci/is-version-number-acceptable.sh
  CHANGELOG.md
  setup.py
Labels: kind:bug

#1025 Amélioration de la lisibilité du supplément familial de traitement
  CHANGELOG.md
  openfisca_france/model/prelevements_obligatoires/prelevements_sociaux/contributions_sociales/activite.py
  openfisca_france/model/prelevements_obligatoires/prelevements_sociaux/cotisations_sociales/travail_fonction_publique.py
  openfisca_france/model/revenus/activite/salarie.py
  openfisca_france/parameters/fonc/supplement_familial/IM_max.yaml
  openfisca_france/parameters/fonc/supplement_familial/IM_min.yaml
  openfisca_france/parameters/fonc/supplement_familial/fixe/enf1.yaml
  openfisca_france/parameters/fonc/supplement_familial/fixe/enf2.yaml
  openfisca_france/parameters/fonc/supplement_familial/fixe/enfsupp.yaml
  openfisca_france/parameters/fonc/supplement_familial/fixe/index.yaml
  openfisca_france/parameters/fonc/supplement_familial/index.yaml
  openfisca_france/parameters/fonc/supplement_familial/prop/enf2.yaml
  openfisca_france/parameters/fonc/supplement_familial/prop/enf3.yaml
  openfisca_france/parameters/fonc/supplement_familial/prop/enfsupp.yaml
  openfisca_france/parameters/fonc/supplement_familial/prop/index.yaml
  openfisca_france/reforms/inversion_directe_salaires.py
  openfisca_france/reforms/inversion_revenus.py
  tests/cotisations_sociales_simulateur_IPP.yaml
Labels: flow:qualified-issues

#1026 Version 22 - Renommage de variables et de paramètres
  CHANGELOG.md
  openfisca_france/decompositions/decomp.xml
  openfisca_france/decompositions/decomp_contrib.xml
  openfisca_france/decompositions/decompositions-multiples.xml
  openfisca_france/model/mesures.py
  openfisca_france/model/prelevements_obligatoires/impot_revenu/ir.py
  openfisca_france/model/prelevements_obligatoires/isf.py
  openfisca_france/model/prelevements_obligatoires/prelevements_sociaux/contributions_sociales/activite.py
  openfisca_france/model/prelevements_obligatoires/prelevements_sociaux/contributions_sociales/capital.py
  openfisca_france/model/prelevements_obligatoires/prelevements_sociaux/cotisations_sociales/travail_fonction_publique.py
  openfisca_france/model/prestations/aides_logement.py
  openfisca_france/model/prestations/minima_sociaux/aah.py
  openfisca_france/model/prestations/minima_sociaux/asi_aspa.py
  openfisca_france/model/prestations/minima_sociaux/rsa.py
  openfisca_france/model/prestations/prestations_familiales/base_ressource.py
  openfisca_france/model/revenus/activite/salarie.py
  openfisca_france/parameters/fonc/supplement_familial/IM_max.yaml
  openfisca_france/parameters/fonc/supplement_familial/IM_min.yaml
  openfisca_france/parameters/fonc/supplement_familial/fixe/enf1.yaml
  openfisca_france/parameters/fonc/supplement_familial/fixe/enf2.yaml
  openfisca_france/parameters/fonc/supplement_familial/fixe/enfsupp.yaml
  openfisca_france/parameters/fonc/supplement_familial/fixe/index.yaml
  openfisca_france/parameters/fonc/supplement_familial/index.yaml
  openfisca_france/parameters/fonc/supplement_familial/prop/enf2.yaml
  openfisca_france/parameters/fonc/supplement_familial/prop/enf3.yaml
  openfisca_france/parameters/fonc/supplement_familial/prop/enfsupp.yaml
  openfisca_france/parameters/fonc/supplement_familial/prop/index.yaml
  openfisca_france/parameters/prestations/minima_sociaux/aah/taux_incapacite.yaml
  openfisca_france/reforms/allocations_familiales_imposables.py
  openfisca_france/reforms/inversion_directe_salaires.py
  openfisca_france/reforms/inversion_revenus.py
  openfisca_france/reforms/landais_piketty_saez.py
  setup.py
  tests/cotisations_sociales_simulateur_IPP.yaml
  tests/formulas/caah.yaml
  tests/formulas/revenu_disponible.yaml
Labels: flow:contrib:doing

#1037 Create a simulation reform to adapt legislation to simulator usage
  CHANGELOG.md
  openfisca_france/model/prestations/logement_social.py
  openfisca_france/reforms/simulation_reform.py
  setup.py
Labels: flow:contrib:doing

#1036 Fait commencer la variable `logement_social_eligible` au 01/01/2017
  CHANGELOG.md
  openfisca_france/model/prestations/logement_social.py
  setup.py
Labels: flow:contrib:doing

#1034 Correction et mise à jour de la taxation des revenus du capital dans l'IRPP
  CHANGELOG.md
  openfisca_france/model/prelevements_obligatoires/impot_revenu/ir.py
  openfisca_france/model/revenus/capital/financier.py
  openfisca_france/model/revenus/capital/plus_value.py
  openfisca_france/parameters/impot_revenu/autre/finpfl.yaml
  openfisca_france/parameters/impot_revenu/autre/index.yaml
  openfisca_france/parameters/impot_revenu/plus_values.yaml
  openfisca_france/parameters/impot_revenu/rvcm/majoration_revenus_reputes_distribues.yaml
  openfisca_france/parameters/impot_revenu/rvcm/taux_forfaitaire.yaml
  setup.py
Labels: flow:contrib:doing

#998 Implémente la réduction du loyer de solidarité
  CHANGELOG.md
  openfisca_france/model/prestations/reduction_loyer_solidarite.py
  openfisca_france/parameters/prestations/reduction_loyer_solidarite/montant/par_zone/zone_1/couples.yaml
  openfisca_france/parameters/prestations/reduction_loyer_solidarite/montant/par_zone/zone_1/famille_1pac.yaml
  openfisca_france/parameters/prestations/reduction_loyer_solidarite/montant/par_zone/zone_1/majoration_par_pac_supp.yaml
  openfisca_france/parameters/prestations/reduction_loyer_solidarite/montant/par_zone/zone_1/personnes_seules.yaml
  openfisca_france/parameters/prestations/reduction_loyer_solidarite/montant/par_zone/zone_2/couples.yaml
  openfisca_france/parameters/prestations/reduction_loyer_solidarite/montant/par_zone/zone_2/famille_1pac.yaml
  openfisca_france/parameters/prestations/reduction_loyer_solidarite/montant/par_zone/zone_2/majoration_par_pac_supp.yaml
  openfisca_france/parameters/prestations/reduction_loyer_solidarite/montant/par_zone/zone_2/personnes_seules.yaml
  openfisca_france/parameters/prestations/reduction_loyer_solidarite/montant/par_zone/zone_3/couples.yaml
  openfisca_france/parameters/prestations/reduction_loyer_solidarite/montant/par_zone/zone_3/famille_1pac.yaml
  openfisca_france/parameters/prestations/reduction_loyer_solidarite/montant/par_zone/zone_3/majoration_par_pac_supp.yaml
  openfisca_france/parameters/prestations/reduction_loyer_solidarite/montant/par_zone/zone_3/personnes_seules.yaml
  openfisca_france/parameters/prestations/reduction_loyer_solidarite/plafond_ressources/par_zone/zone_1/couples.yaml
  openfisca_france/parameters/prestations/reduction_loyer_solidarite/plafond_ressources/par_zone/zone_1/famille_1pac.yaml
  openfisca_france/parameters/prestations/reduction_loyer_solidarite/plafond_ressources/par_zone/zone_1/famille_2pac.yaml
  openfisca_france/parameters/prestations/reduction_loyer_solidarite/plafond_ressources/par_zone/zone_1/famille_3pac.yaml
  openfisca_france/parameters/prestations/reduction_loyer_solidarite/plafond_ressources/par_zone/zone_1/famille_4pac.yaml
  openfisca_france/parameters/prestations/reduction_loyer_solidarite/plafond_ressources/par_zone/zone_1/famille_5pac.yaml
  openfisca_france/parameters/prestations/reduction_loyer_solidarite/plafond_ressources/par_zone/zone_1/famille_6pac.yaml
  openfisca_france/parameters/prestations/reduction_loyer_solidarite/plafond_ressources/par_zone/zone_1/majoration_par_pac_supp.yaml
  openfisca_france/parameters/prestations/reduction_loyer_solidarite/plafond_ressources/par_zone/zone_1/personnes_seules.yaml
  openfisca_france/parameters/prestations/reduction_loyer_solidarite/plafond_ressources/par_zone/zone_2/couples.yaml
  openfisca_france/parameters/prestations/reduction_loyer_solidarite/plafond_ressources/par_zone/zone_2/famille_1pac.yaml
  openfisca_france/parameters/prestations/reduction_loyer_solidarite/plafond_ressources/par_zone/zone_2/famille_2pac.yaml
  openfisca_france/parameters/prestations/reduction_loyer_solidarite/plafond_ressources/par_zone/zone_2/famille_3pac.yaml
  openfisca_france/parameters/prestations/reduction_loyer_solidarite/plafond_ressources/par_zone/zone_2/famille_4pac.yaml
  openfisca_france/parameters/prestations/reduction_loyer_solidarite/plafond_ressources/par_zone/zone_2/famille_5pac.yaml
  openfisca_france/parameters/prestations/reduction_loyer_solidarite/plafond_ressources/par_zone/zone_2/famille_6pac.yaml
  openfisca_france/parameters/prestations/reduction_loyer_solidarite/plafond_ressources/par_zone/zone_2/majoration_par_pac_supp.yaml
  openfisca_france/parameters/prestations/reduction_loyer_solidarite/plafond_ressources/par_zone/zone_2/personnes_seules.yaml
  openfisca_france/parameters/prestations/reduction_loyer_solidarite/plafond_ressources/par_zone/zone_3/couples.yaml
  openfisca_france/parameters/prestations/reduction_loyer_solidarite/plafond_ressources/par_zone/zone_3/famille_1pac.yaml
  openfisca_france/parameters/prestations/reduction_loyer_solidarite/plafond_ressources/par_zone/zone_3/famille_2pac.yaml
  openfisca_france/parameters/prestations/reduction_loyer_solidarite/plafond_ressources/par_zone/zone_3/famille_3pac.yaml
  openfisca_france/parameters/prestations/reduction_loyer_solidarite/plafond_ressources/par_zone/zone_3/famille_4pac.yaml
  openfisca_france/parameters/prestations/reduction_loyer_solidarite/plafond_ressources/par_zone/zone_3/famille_5pac.yaml
  openfisca_france/parameters/prestations/reduction_loyer_solidarite/plafond_ressources/par_zone/zone_3/famille_6pac.yaml
  openfisca_france/parameters/prestations/reduction_loyer_solidarite/plafond_ressources/par_zone/zone_3/majoration_par_pac_supp.yaml
  openfisca_france/parameters/prestations/reduction_loyer_solidarite/plafond_ressources/par_zone/zone_3/personnes_seules.yaml
  setup.py
  tests/formulas/rls.yaml
Labels: flow:contrib:doing
