Repository openfisca/openfisca-france, pull requests merged in 2018-03, with the labels that each got.

#924 Ajout du barème pour le chèque énergie
  CHANGELOG.md
  openfisca_france/conf/cache_blacklist.py
  openfisca_france/model/mesures.py
  openfisca_france/model/prestations/cheque_energie.py
  openfisca_france/parameters/cheque_energie.yaml
  setup.py
  tests/formulas/cheque_energie/montant.yaml
  tests/formulas/cheque_energie/unites_consommation.yaml
Labels: flow:contribution-backlog

#909 Ipp 3 : Minor updates of tax credit and tax reductions
  CHANGELOG.md
  openfisca_france/model/prelevements_obligatoires/impot_revenu/credits_impot.py
  openfisca_france/model/prelevements_obligatoires/impot_revenu/ir.py
  openfisca_france/model/prelevements_obligatoires/impot_revenu/reductions_impot.py
  openfisca_france/model/prelevements_obligatoires/impot_revenu/variables_reductions_credits.py
  openfisca_france/model/revenus/capital/plus_value.py
  setup.py
Labels: flow:contribution-backlog

#922 Migre la dernière formule vers la syntaxe standard 🎉 🎉
  CHANGELOG.md
  circle.yml
  openfisca_france/model/prestations/minima_sociaux/cmu.py
  setup.py
  tests/formulas/cmu.yaml
Labels: flow:team-backlog

#911 Ipp 5 : Mise à jour de la réduction d'IR pour investissements forestiers
  CHANGELOG.md
  openfisca_france/model/prelevements_obligatoires/impot_revenu/reductions_impot.py
  openfisca_france/model/prelevements_obligatoires/impot_revenu/variables_reductions_credits.py
  setup.py
Labels: contrib:ipp, flow:contrib:doing, kind:evolution, scope:tax

#912 Ipp 6 : Update réductions d'IR spécial DOM-TOM
  CHANGELOG.md
  openfisca_france/model/prelevements_obligatoires/impot_revenu/reductions_impot.py
  openfisca_france/model/prelevements_obligatoires/impot_revenu/variables_reductions_credits.py
  setup.py
Labels: contrib:ipp, flow:contrib:doing, kind:evolution, scope:tax
