Repository openfisca/openfisca-france, pull requests merged in 2019-07, with the labels that each got.

#1354 Ajustement de 1€ sur la réfaction sous condition RFR
  CHANGELOG.md
  openfisca_france/parameters/impot_revenu/plafond_qf/reduction_ss_condition_revenus/seuil1.yaml
  openfisca_france/parameters/impot_revenu/plafond_qf/reduction_ss_condition_revenus/seuil2.yaml
  setup.py
Labels: kind:evolution, level:starter

#1361 Améliore les conditions d'éligibilité à la PPA pour les couples avec étudiant
  CHANGELOG.md
  openfisca_france/conf/cache_blacklist.py
  openfisca_france/model/prestations/minima_sociaux/ppa.py
  setup.py
Labels: kind:improvement

#1362 Fusion des aides des compléments de ressources à l’AAH au 1er Décembre 2019
  CHANGELOG.md
  openfisca_france/model/prestations/minima_sociaux/aah.py
  setup.py
  tests/formulas/complement_aah.yaml
Labels: contrib:msa, kind:evolution
