Repository openfisca/openfisca-france, pull requests merged in 2019-10, with the labels that each got.

#1378 Rectifie la revalorisation paramètres aides au logement au 01/10/19
  CHANGELOG.md
  openfisca_france/parameters/prestations/aides_logement/al_charge/personne_isolee_ou_menage_seul/cas_des_colocataires_ou_des_proprietaires_1.yaml
  openfisca_france/parameters/prestations/aides_logement/forfait_charges/cas_general.yaml
  openfisca_france/parameters/prestations/aides_logement/forfait_charges/majoration_par_enfant.yaml
  openfisca_france/parameters/prestations/aides_logement/loyers_plafond/par_zone/zone_1/couples.yaml
  openfisca_france/parameters/prestations/aides_logement/loyers_plafond/par_zone/zone_1/majoration_par_enf_supp.yaml
  openfisca_france/parameters/prestations/aides_logement/loyers_plafond/par_zone/zone_1/personnes_seules.yaml
  openfisca_france/parameters/prestations/aides_logement/loyers_plafond/par_zone/zone_1/un_enfant.yaml
  openfisca_france/parameters/prestations/aides_logement/loyers_plafond/par_zone/zone_2/couples.yaml
  openfisca_france/parameters/prestations/aides_logement/loyers_plafond/par_zone/zone_2/majoration_par_enf_supp.yaml
  openfisca_france/parameters/prestations/aides_logement/loyers_plafond/par_zone/zone_2/personnes_seules.yaml
  openfisca_france/parameters/prestations/aides_logement/loyers_plafond/par_zone/zone_2/un_enfant.yaml
  openfisca_france/parameters/prestations/aides_logement/loyers_plafond/par_zone/zone_3/couples.yaml
  openfisca_france/parameters/prestations/aides_logement/loyers_plafond/par_zone/zone_3/majoration_par_enf_supp.yaml
  openfisca_france/parameters/prestations/aides_logement/loyers_plafond/par_zone/zone_3/personnes_seules.yaml
  openfisca_france/parameters/prestations/aides_logement/loyers_plafond/par_zone/zone_3/un_enfant.yaml
  openfisca_france/parameters/prestations/aides_logement/participation_min/montant_forfaitaire.yaml
  openfisca_france/parameters/prestations/al_plafonds_accession/zone_1/menage_ou_isole_avec_1_enfant.yaml
  openfisca_france/parameters/prestations/al_plafonds_accession/zone_1/menage_ou_isole_avec_2_enfants.yaml
  openfisca_france/parameters/prestations/al_plafonds_accession/zone_1/menage_ou_isole_avec_3_enfants.yaml
  openfisca_france/parameters/prestations/al_plafonds_accession/zone_1/menage_ou_isole_avec_4_enfants.yaml
  openfisca_france/parameters/prestations/al_plafonds_accession/zone_1/menage_ou_isole_avec_5_enfants.yaml
  openfisca_france/parameters/prestations/al_plafonds_accession/zone_1/menage_ou_isole_par_enfant_en_plus.yaml
  openfisca_france/parameters/prestations/al_plafonds_accession/zone_1/menage_seul.yaml
  openfisca_france/parameters/prestations/al_plafonds_accession/zone_1/personne_isolee_sans_enfant.yaml
  openfisca_france/parameters/prestations/al_plafonds_accession/zone_2/menage_ou_isole_avec_1_enfant.yaml
  openfisca_france/parameters/prestations/al_plafonds_accession/zone_2/menage_ou_isole_avec_2_enfants.yaml
  openfisca_france/parameters/prestations/al_plafonds_accession/zone_2/menage_ou_isole_avec_3_enfants.yaml
  openfisca_france/parameters/prestations/al_plafonds_accession/zone_2/menage_ou_isole_avec_4_enfants.yaml
  openfisca_france/parameters/prestations/al_plafonds_accession/zone_2/menage_ou_isole_avec_5_enfants.yaml
  openfisca_france/parameters/prestations/al_plafonds_accession/zone_2/menage_ou_isole_par_enfant_en_plus.yaml
  openfisca_france/parameters/prestations/al_plafonds_accession/zone_2/menage_seul.yaml
  openfisca_france/parameters/prestations/al_plafonds_accession/zone_2/personne_isolee_sans_enfant.yaml
  openfisca_france/parameters/prestations/al_plafonds_accession/zone_3/menage_ou_isole_avec_1_enfant.yaml
  openfisca_france/parameters/prestations/al_plafonds_accession/zone_3/menage_ou_isole_avec_2_enfants.yaml
  openfisca_france/parameters/prestations/al_plafonds_accession/zone_3/menage_ou_isole_avec_3_enfants.yaml
  openfisca_france/parameters/prestations/al_plafonds_accession/zone_3/menage_ou_isole_avec_4_enfants.yaml
  openfisca_france/parameters/prestations/al_plafonds_accession/zone_3/menage_ou_isole_avec_5_enfants.yaml
  openfisca_france/parameters/prestations/al_plafonds_accession/zone_3/menage_ou_isole_par_enfant_en_plus.yaml
  openfisca_france/parameters/prestations/al_plafonds_accession/zone_3/menage_seul.yaml
  openfisca_france/parameters/prestations/al_plafonds_accession/zone_3/personne_isolee_sans_enfant.yaml
  openfisca_france/parameters/prestations/al_plafonds_logement_foyer/conventionne/zone_1.yaml
  openfisca_france/parameters/prestations/al_plafonds_logement_foyer/conventionne/zone_2.yaml
  openfisca_france/parameters/prestations/al_plafonds_logement_foyer/conventionne/zone_3.yaml
  openfisca_france/parameters/prestations/al_plafonds_logement_foyer/personne_agee/couple.yaml
  openfisca_france/parameters/prestations/al_plafonds_logement_foyer/personne_agee/personne_isolee.yaml
  openfisca_france/parameters/prestations/al_plafonds_logement_foyer_crous/non_rehabilitee/couple.yaml
  openfisca_france/parameters/prestations/al_plafonds_logement_foyer_crous/non_rehabilitee/personne_isolee.yaml
  openfisca_france/parameters/prestations/al_plafonds_logement_foyer_crous/rehabilitee/couple.yaml
  openfisca_france/parameters/prestations/al_plafonds_logement_foyer_crous/rehabilitee/personne_isolee.yaml
  setup.py
Labels: contrib:msa, kind:evolution

#1374 Corrige la formule APA urgence (institution)
  CHANGELOG.md
  openfisca_france/model/prelevements_obligatoires/prelevements_sociaux/contributions_sociales/remplacement.py
  openfisca_france/model/prestations/autonomie.py
  setup.py
  tests/formulas/autonomie.yaml
Labels: kind:bug

#1380 Améliore calcul identifier tarif GIR de personne APA
  CHANGELOG.md
  openfisca_france/model/prestations/autonomie.py
  setup.py
  tests/formulas/autonomie.yaml
Labels: kind:evolution

#1335 Divers update (IR 2019 sur revenus 2018)
  CHANGELOG.md
  openfisca_france/model/prelevements_obligatoires/impot_revenu/charges_deductibles.py
  openfisca_france/model/prelevements_obligatoires/impot_revenu/credits_impot.py
  openfisca_france/model/prelevements_obligatoires/impot_revenu/reductions_impot.py
  openfisca_france/model/prelevements_obligatoires/impot_revenu/variables_reductions_credits.py
  openfisca_france/model/prelevements_obligatoires/prelevements_sociaux/cotisations_sociales/exonerations.py
  openfisca_france/model/prestations/aides_logement.py
  openfisca_france/model/prestations/minima_sociaux/aah.py
  openfisca_france/model/prestations/minima_sociaux/cs/cmu.py
  openfisca_france/model/prestations/minima_sociaux/ppa.py
  openfisca_france/model/revenus/capital/financier.py
  openfisca_france/scripts/parameters/explore_parameters_unit.py
  openfisca_france/scripts/parameters/reduce_parameters_paths.py
  setup.py
  tests/test_coefficient.py
Labels: kind:evolution
