Repository openfisca/openfisca-france, pull requests merged in 2019-05, with the labels that each got.

#1317 Corrige des références et descriptions
  CHANGELOG.md
  openfisca_france/reforms/de_net_a_brut.py
  setup.py
Labels: flow:qualified-issues-fr

#1319 Revalorisation du Revenu de solidarité active (RSA) au 1er avril 2019 en métropole
  CHANGELOG.md
  openfisca_france/parameters/prestations/minima_sociaux/rsa/montant_de_base_du_rsa.yaml
  setup.py
Labels: contrib:msa, flow:delivery

#1328 Revalorisation de l’Allocation de solidarité spécifique (ASS) au 1er avril 2019 en métropole
  CHANGELOG.md
  openfisca_france/parameters/prestations/minima_sociaux/ass/montant_plein.yaml
  setup.py
  tests/formulas/ass_interessement.yaml
Labels: contrib:msa
