Repository openfisca/openfisca-france, pull requests merged in 2019-04, with the labels that each got.

#1261 Supprime les attributs de type base_function
  CHANGELOG.md
  openfisca_france/model/caracteristiques_socio_demographiques/demographie.py
  openfisca_france/model/prelevements_obligatoires/impot_revenu/ir.py
  openfisca_france/model/prestations/minima_sociaux/rsa.py
  openfisca_france/model/revenus/activite/salarie.py
  openfisca_france/model/revenus/capital/financier.py
  openfisca_france/model/revenus/capital/foncier.py
  setup.py
  tests/fiches_de_paie/apprenti.yaml
  tests/formulas/aides_logement_2018.yaml
  tests/formulas/exoneration_cotisations_employeur_apprenti.yaml
  tests/formulas/exoneration_cotisations_employeur_zrd.yaml
  tests/formulas/exoneration_cotisations_employeur_zrr.yaml
  tests/formulas/exoneration_is_creation_zrr.yaml
  tests/formulas/garde_alternee.yaml
  tests/formulas/ppa.yaml
  tests/formulas/remuneration_apprenti.yaml
  tests/formulas/rsa.yaml
  tests/formulas/rsa/rsa_2017.yaml
  tests/formulas/rsa/rsa_couple.yaml
  tests/mes-aides.gouv.fr/test_mes_aides_54212b32fb35830200b31327.yaml
  tests/mes-aides.gouv.fr/test_mes_aides_54212b9dfb35830200b3132e.yaml
  tests/mes-aides.gouv.fr/test_mes_aides_542134d3fb35830200b31345.yaml
  tests/mes-aides.gouv.fr/test_mes_aides_5421356afb35830200b3134c.yaml
  tests/mes-aides.gouv.fr/test_mes_aides_54367da883a4916e4d5a13a3.yaml
  tests/mes-aides.gouv.fr/test_mes_aides_5436807f2f6a1b774dad2a71.yaml
  tests/mes-aides.gouv.fr/test_mes_aides_545a3741d550a12d2ae7b68c.yaml
  tests/mes-aides.gouv.fr/test_mes_aides_546490a716951c7e7065a5a1.yaml
  tests/mes-aides.gouv.fr/test_mes_aides_54bfdaf4d337b5d372377d30.yaml
  tests/test_coefficient.py
Labels: flow:discovery

#1302 Revalorisations PFs au 1er Avril 2019
  CHANGELOG.md
  openfisca_france/parameters/cmu/plafond_base.yaml
  openfisca_france/parameters/prestations/minima_sociaux/asi/montant_couple.yaml
  openfisca_france/parameters/prestations/minima_sociaux/asi/montant_seul.yaml
  openfisca_france/parameters/prestations/minima_sociaux/asi/plafond_ressource_couple.yaml
  openfisca_france/parameters/prestations/minima_sociaux/asi/plafond_ressource_seul.yaml
  openfisca_france/parameters/prestations/prestations_familiales/af/bmaf.yaml
  setup.py
Labels: contrib:msa, flow:reviewing

#1305 Exige flake8 >= 3.7 et pycodestyle implicitement
  CHANGELOG.md
  setup.py
Labels: flow:qualified-issues-fr

#1314 Met à jour les barèmes de l'IR 2018
  CHANGELOG.md
  openfisca_france/parameters/impot_revenu/bareme.yaml
  setup.py
Labels: flow:delivery, kind:evolution, level:starter
