Repository openfisca/openfisca-france, pull requests merged in 2019-02, with the labels that each got.

#1264 Modification du calcul du plafond de ressources pour les bénéficiaires de l’allocation adulte handicapé en couple
  CHANGELOG.md
  openfisca_france/model/prestations/minima_sociaux/aah.py
  openfisca_france/parameters/prestations/minima_sociaux/aah/majoration_du_plafond_pour_un_couple.yaml
  openfisca_france/parameters/prestations/minima_sociaux/aah/montant.yaml
  setup.py
  tests/formulas/aah_couple.yaml
Labels: contrib:msa, flow:reviewing

#1265 Ajoute des références législatives à la PPA
  CHANGELOG.md
  openfisca_france/model/prestations/minima_sociaux/ppa.py
  setup.py
Labels: flow:reviewing

#1271 Réactive le crédit d'impôt pour cotisations syndicales
  CHANGELOG.md
  openfisca_france/model/prelevements_obligatoires/impot_revenu/credits_impot.py
  openfisca_france/model/prelevements_obligatoires/impot_revenu/reductions_impot.py
  setup.py
  tests/impot_revenu/cotsyn.yaml
Labels: flow:reviewing

#1280 Revalorisation de l'allocation de solidarité aux personnes âgées au 1er janvier 2019
  CHANGELOG.md
  openfisca_france/parameters/prestations/minima_sociaux/aspa/montant_annuel_couple.yaml
  openfisca_france/parameters/prestations/minima_sociaux/aspa/montant_annuel_seul.yaml
  openfisca_france/parameters/prestations/minima_sociaux/aspa/plafond_ressources_couple.yaml
  openfisca_france/parameters/prestations/minima_sociaux/aspa/plafond_ressources_seul.yaml
  setup.py
Labels: contrib:msa

#1277 Ajoute badges au README.md
  README.md
  setup.py
Labels: flow:qualified-issues-fr, kind:com, level:starter

#1272 Corrige le calcul des revenus bruts
  CHANGELOG.md
  openfisca_france/model/mesures.py
  setup.py
Labels: flow:reviewing

#1227 Adapte France à Core 26
  CHANGELOG.md
  openfisca_france/decompositions/__init__.py
  openfisca_france/decompositions/decomp.xml
  openfisca_france/decompositions/decomp_contrib.xml
  openfisca_france/decompositions/decomp_prestations.xml
  openfisca_france/decompositions/decompositions-multiples.xml
  openfisca_france/decompositions/fiche_de_paie_decomposition.xml
  openfisca_france/france_taxbenefitsystem.py
  openfisca_france/reforms/inversion_revenus.py
  openfisca_france/scenarios.py
  setup.py
  tests/reforms/test_allocations_familliales_imposables.py
  tests/reforms/test_cesthra.py
  tests/reforms/test_landais_piketty_saez.py
  tests/reforms/test_parametric_reform.py
  tests/reforms/test_plf2015.py
  tests/reforms/test_plf2016.py
  tests/reforms/test_plf2016_ayrault_muet.py
  tests/reforms/test_plfr2014.py
  tests/reforms/test_trannoy_wasmer.py
  tests/test_basics.py
  tests/test_coefficient.py
  tests/test_decomposition_fiches_de_paie.py
  tests/test_entities.py
  tests/test_nb_enfants.py
  tests/test_repairs.py
  tests/test_suggestions.py
  tests/test_tax_rates.py
  tests/utils.py
Labels: flow:reviewing

#1275 Conditions spécifiques à Mayotte pour l’allocation de solidarité spécifique (ASS)
  CHANGELOG.md
  openfisca_france/model/prestations/minima_sociaux/ass.py
  openfisca_france/parameters/prestations/minima_sociaux/ass/montant_plein_mayotte.yaml
  setup.py
  tests/formulas/ass_mayotte.yaml
Labels: contrib:msa, flow:reviewing
