Repository openfisca/openfisca-france, pull requests merged in 2019-01, with the labels that each got.

#1247 Met à jour les parametres de la PPA suite à revalorisation exceptionnelle de 2019
  CHANGELOG.md
  openfisca_france/parameters/cotsoc/gen/smic_h_b.yaml
  openfisca_france/parameters/prestations/minima_sociaux/ppa/bonification/seuil_max_bonification.yaml
  openfisca_france/parameters/prestations/minima_sociaux/ppa/bonification/taux_bonification_max.yaml
  setup.py
Labels: contrib:msa

#1244 Ajoute des références législatives pour l'ASS
  CHANGELOG.md
  openfisca_france/model/prestations/minima_sociaux/ass.py
  setup.py
Labels: flow:reviewing, kind:documentation

#1233 Corrige un calcul des aides au logement
  CHANGELOG.md
  openfisca_france/model/prestations/aides_logement.py
  setup.py
Labels: flow:delivery

#1216 Améliore revenus fonciers
  CHANGELOG.md
  openfisca_france/france_taxbenefitsystem.py
  openfisca_france/model/mesures.py
  openfisca_france/model/prelevements_obligatoires/impot_revenu/ir.py
  openfisca_france/model/prelevements_obligatoires/isf.py
  openfisca_france/model/prestations/aides_logement.py
  openfisca_france/model/prestations/prestations_familiales/base_ressource.py
  openfisca_france/model/revenus/capital/foncier.py
  setup.py
  tests/capital/cotisations_sociales_capital.yaml
  tests/impot_revenu/revenus_fonciers.yaml
Labels: flow:reviewing

#1243 Prends en compte les ressources du capital dans le calcul de la prime d'activité
  CHANGELOG.md
  openfisca_france/model/prestations/minima_sociaux/ppa.py
  setup.py
  tests/formulas/ppa.yaml
  tests/formulas/ppa/ppa_ressources_hors_activite_individu.yaml
Labels: flow:reviewing, kind:evolution

#1253 Eligibilite rsa jeune
  CHANGELOG.md
  openfisca_france/model/prestations/minima_sociaux/rsa.py
  setup.py
  tests/formulas/rsa/rsa_jeune.yaml
Labels: flow:reviewing

#1255 Revalorisation du complément familial au 1er janvier 2019
  CHANGELOG.md
  openfisca_france/parameters/prestations/prestations_familiales/cf/majoration_plafond_biact_isole.yaml
  openfisca_france/parameters/prestations/prestations_familiales/cf/plafond_de_ressources_0_enfant.yaml
  setup.py
Labels: contrib:msa, flow:reviewing

#1257 Revalorisation de la prestation d'accueil du jeune enfant (PAJE) au 1er janvier 2019
  CHANGELOG.md
  openfisca_france/parameters/prestations/prestations_familiales/cf/majoration_plafond_biact_isole.yaml
  openfisca_france/parameters/prestations/prestations_familiales/paje/base/apres_2014/taux_partiel/plaf.yaml
  openfisca_france/parameters/prestations/prestations_familiales/paje/base/apres_2014/taux_partiel/plaf_maj.yaml
  openfisca_france/parameters/prestations/prestations_familiales/paje/base/apres_2014/taux_plein/plaf.yaml
  openfisca_france/parameters/prestations/prestations_familiales/paje/base/apres_2014/taux_plein/plaf_maj.yaml
  openfisca_france/parameters/prestations/prestations_familiales/paje/base/apres_2018/taux_partiel/plaf.yaml
  openfisca_france/parameters/prestations/prestations_familiales/paje/base/apres_2018/taux_partiel/plaf_maj.yaml
  openfisca_france/parameters/prestations/prestations_familiales/paje/base/apres_2018/taux_plein/plaf.yaml
  openfisca_france/parameters/prestations/prestations_familiales/paje/clmg.yaml
  openfisca_france/parameters/prestations/prestations_familiales/paje/montant_maximale_de_la_prise_en_charge/enfant_de_3_a_6_ans.yaml
  openfisca_france/parameters/prestations/prestations_familiales/paje/montant_maximale_de_la_prise_en_charge/enfant_de_moins_de_3_ans.yaml
  setup.py
Labels: contrib:msa

#1259 Revalorisation des aides au logement au 1er janvier 2019
  CHANGELOG.md
  openfisca_france/parameters/prestations/aides_logement/R0/taux1pac.yaml
  openfisca_france/parameters/prestations/aides_logement/R0/taux2pac.yaml
  openfisca_france/parameters/prestations/aides_logement/R0/taux3pac.yaml
  openfisca_france/parameters/prestations/aides_logement/R0/taux4pac.yaml
  openfisca_france/parameters/prestations/aides_logement/R0/taux5pac.yaml
  openfisca_france/parameters/prestations/aides_logement/R0/taux6pac.yaml
  openfisca_france/parameters/prestations/aides_logement/R0/taux_couple.yaml
  openfisca_france/parameters/prestations/aides_logement/R0/taux_seul.yaml
  openfisca_france/parameters/prestations/aides_logement/ressources/dar_8.yaml
  openfisca_france/parameters/prestations/aides_logement/ressources/dar_9.yaml
  openfisca_france/parameters/prestations/reduction_loyer_solidarite/montant/par_zone/zone_1/couples.yaml
  openfisca_france/parameters/prestations/reduction_loyer_solidarite/montant/par_zone/zone_1/famille_1pac.yaml
  openfisca_france/parameters/prestations/reduction_loyer_solidarite/montant/par_zone/zone_1/majoration_par_pac_supp.yaml
  openfisca_france/parameters/prestations/reduction_loyer_solidarite/montant/par_zone/zone_1/personnes_seules.yaml
  openfisca_france/parameters/prestations/reduction_loyer_solidarite/montant/par_zone/zone_2/couples.yaml
  openfisca_france/parameters/prestations/reduction_loyer_solidarite/montant/par_zone/zone_2/famille_1pac.yaml
  openfisca_france/parameters/prestations/reduction_loyer_solidarite/montant/par_zone/zone_2/majoration_par_pac_supp.yaml
  openfisca_france/parameters/prestations/reduction_loyer_solidarite/montant/par_zone/zone_2/personnes_seules.yaml
  openfisca_france/parameters/prestations/reduction_loyer_solidarite/montant/par_zone/zone_3/couples.yaml
  openfisca_france/parameters/prestations/reduction_loyer_solidarite/montant/par_zone/zone_3/famille_1pac.yaml
  openfisca_france/parameters/prestations/reduction_loyer_solidarite/montant/par_zone/zone_3/majoration_par_pac_supp.yaml
  openfisca_france/parameters/prestations/reduction_loyer_solidarite/montant/par_zone/zone_3/personnes_seules.yaml
  openfisca_france/parameters/prestations/reduction_loyer_solidarite/plafond_ressources/par_zone/zone_1/couples.yaml
  openfisca_france/parameters/prestations/reduction_loyer_solidarite/plafond_ressources/par_zone/zone_1/famille_1pac.yaml
  openfisca_france/parameters/prestations/reduction_loyer_solidarite/plafond_ressources/par_zone/zone_1/famille_2pac.yaml
  openfisca_france/parameters/prestations/reduction_loyer_solidarite/plafond_ressources/par_zone/zone_1/famille_3pac.yaml
  openfisca_france/parameters/prestations/reduction_loyer_solidarite/plafond_ressources/par_zone/zone_1/famille_4pac.yaml
  openfisca_france/parameters/prestations/reduction_loyer_solidarite/plafond_ressources/par_zone/zone_1/famille_5pac.yaml
  openfisca_france/parameters/prestations/reduction_loyer_solidarite/plafond_ressources/par_zone/zone_1/famille_6pac.yaml
  openfisca_france/parameters/prestations/reduction_loyer_solidarite/plafond_ressources/par_zone/zone_1/majoration_par_pac_supp.yaml
  openfisca_france/parameters/prestations/reduction_loyer_solidarite/plafond_ressources/par_zone/zone_1/personnes_seules.yaml
  openfisca_france/parameters/prestations/reduction_loyer_solidarite/plafond_ressources/par_zone/zone_2/couples.yaml
  openfisca_france/parameters/prestations/reduction_loyer_solidarite/plafond_ressources/par_zone/zone_2/famille_1pac.yaml
  openfisca_france/parameters/prestations/reduction_loyer_solidarite/plafond_ressources/par_zone/zone_2/famille_2pac.yaml
  openfisca_france/parameters/prestations/reduction_loyer_solidarite/plafond_ressources/par_zone/zone_2/famille_3pac.yaml
  openfisca_france/parameters/prestations/reduction_loyer_solidarite/plafond_ressources/par_zone/zone_2/famille_4pac.yaml
  openfisca_france/parameters/prestations/reduction_loyer_solidarite/plafond_ressources/par_zone/zone_2/famille_5pac.yaml
  openfisca_france/parameters/prestations/reduction_loyer_solidarite/plafond_ressources/par_zone/zone_2/famille_6pac.yaml
  openfisca_france/parameters/prestations/reduction_loyer_solidarite/plafond_ressources/par_zone/zone_2/majoration_par_pac_supp.yaml
  openfisca_france/parameters/prestations/reduction_loyer_solidarite/plafond_ressources/par_zone/zone_2/personnes_seules.yaml
  openfisca_france/parameters/prestations/reduction_loyer_solidarite/plafond_ressources/par_zone/zone_3/couples.yaml
  openfisca_france/parameters/prestations/reduction_loyer_solidarite/plafond_ressources/par_zone/zone_3/famille_1pac.yaml
  openfisca_france/parameters/prestations/reduction_loyer_solidarite/plafond_ressources/par_zone/zone_3/famille_2pac.yaml
  openfisca_france/parameters/prestations/reduction_loyer_solidarite/plafond_ressources/par_zone/zone_3/famille_3pac.yaml
  openfisca_france/parameters/prestations/reduction_loyer_solidarite/plafond_ressources/par_zone/zone_3/famille_4pac.yaml
  openfisca_france/parameters/prestations/reduction_loyer_solidarite/plafond_ressources/par_zone/zone_3/famille_5pac.yaml
  openfisca_france/parameters/prestations/reduction_loyer_solidarite/plafond_ressources/par_zone/zone_3/famille_6pac.yaml
  openfisca_france/parameters/prestations/reduction_loyer_solidarite/plafond_ressources/par_zone/zone_3/majoration_par_pac_supp.yaml
  openfisca_france/parameters/prestations/reduction_loyer_solidarite/plafond_ressources/par_zone/zone_3/personnes_seules.yaml
  setup.py
Labels: contrib:msa, flow:reviewing

#1260 Effectue les étapes d'intégration continue sur Python 3 seulement
  .circleci/config.yml
Labels: flow:reviewing
