Repository openfisca/openfisca-france, pull requests merged in 2019-03, with the labels that each got.

#1269 Fiabilisation générale du calcul des aides au logement
  CHANGELOG.md
  openfisca_france/model/prestations/aides_logement.py
  setup.py
  tests/formulas/aides_logement_fiabilisation.yaml
  tests/mes-aides.gouv.fr/test_mes_aides_54d396fd4ec19fce4422725e.yaml
  tests/mes-aides.gouv.fr/test_mes_aides_559d204131741cd84c323303.yaml
  tests/mes-aides.gouv.fr/test_mes_aides_55f02b141e52de32043695f7.yaml
Labels: contrib:msa, flow:re-reviewing

#1274 Application d'un montant minimal de l'AAH en cas d'hospitalisation/incarceration
  CHANGELOG.md
  openfisca_france/model/caracteristiques_socio_demographiques/capacite_travail.py
  openfisca_france/model/prestations/minima_sociaux/aah.py
  openfisca_france/model/prestations/minima_sociaux/asi_aspa.py
  openfisca_france/parameters/prestations/minima_sociaux/aah/mva.yaml
  openfisca_france/parameters/prestations/minima_sociaux/aah/taux_aah_hospitalise_ou_incarcere.yaml
  openfisca_france/parameters/prestations/minima_sociaux/aah/taux_capacite_travail.yaml
  openfisca_france/parameters/prestations/minima_sociaux/caah/garantie_ressources.yaml
  setup.py
  tests/formulas/complement_aah.yaml
Labels: contrib:msa, flow:re-reviewing

#1286 Supprime la TEHR à partir de 2015
  CHANGELOG.md
  openfisca_france/model/prelevements_obligatoires/prelevements_sociaux/contributions_sociales/activite.py
  openfisca_france/model/prelevements_obligatoires/prelevements_sociaux/cotisations_sociales/travail_non_salarie.py
  openfisca_france/parameters/cotsoc/tehr.yaml
  setup.py
Labels: flow:support

#1289 Nettoie le CHANGELOG
  CHANGELOG.md
  setup.py
Labels: flow:reviewing

#1284 Supprime extra_param du calcul du RSA
  CHANGELOG.md
  openfisca_france/model/prelevements_obligatoires/prelevements_sociaux/cotisations_sociales/travail_prive.py
  openfisca_france/model/prestations/minima_sociaux/rsa.py
  setup.py
  tests/formulas/rsa.yaml
  tests/formulas/rsa/rsa_2017.yaml
Labels: flow:qualified-issues-fr

#1270 Intégration du calcul de la rente d'accident du travail
  CHANGELOG.md
  openfisca_france/model/revenus/remplacement/rente_accident_travail.py
  openfisca_france/parameters/accident_travail/rente/salaire_net/bareme.yaml
  openfisca_france/parameters/accident_travail/rente/salaire_net/salaire_minimum.yaml
  openfisca_france/parameters/accident_travail/rente/taux/bareme.yaml
  openfisca_france/parameters/accident_travail/rente/taux/capital_representatif.yaml
  openfisca_france/parameters/accident_travail/rente/taux/indemnite_accident_travail.yaml
  openfisca_france/parameters/accident_travail/rente/taux/pcrtp.yaml
  openfisca_france/parameters/accident_travail/rente/taux/taux_minimum.yaml
  setup.py
  tests/formulas/rente_at.yaml
Labels: contrib:msa, flow:reviewing

#1291 Améliore la base ressources des revenus du capital de la PPA
  CHANGELOG.md
  openfisca_france/model/prestations/minima_sociaux/ppa.py
  setup.py
  tests/formulas/ppa.yaml
  tests/formulas/ppa/ppa_ressources_hors_activite_individu.yaml
Labels: flow:qualified-issues-fr
