Repository openfisca/openfisca-france, pull requests merged in 2020-01, with the labels that each got.

#1400 Corrige le déploiement PyPi
  CHANGELOG.md
  setup.py
Labels: kind:devops

#1399 Corrige le calcul de la réduction d'impôt sous conditions de ressources
  CHANGELOG.md
  openfisca_france/model/prelevements_obligatoires/impot_revenu/ir.py
  setup.py
  tests/calculateur_impots/yaml/reduc_sous_conditions_ressources.yaml
Labels: kind:evolution

#1395 Corrige zone_logement_social pour retourner un vecteur
  CHANGELOG.md
  openfisca_france/model/prestations/logement_social.py
  setup.cfg
  setup.py
Labels: kind:improvement, level:intermediate

#1402 Suppression de période en dur dans la CSA
  CHANGELOG.md
  openfisca_france/model/prelevements_obligatoires/prelevements_sociaux/taxes_salaires_main_oeuvre.py
  setup.py
  tests/formulas/csa.yaml
Labels: kind:improvement

#1396 Ajoute un template pour les issues
  .github/ISSUE_TEMPLATE.md
Labels: kind:documentation, level:starter

#1393 Calcule la tranche et le taux marginal IR
  CHANGELOG.md
  openfisca_france/model/prelevements_obligatoires/impot_revenu/ir.py
  setup.py
  tests/formulas/ir_taux_marginal.yaml
  tests/formulas/ir_tranche.yaml
Labels: kind:solution, level:intermediate

#1409 Améliore la prise en compte des bourses sur critères sociaux pour la CSS
  CHANGELOG.md
  openfisca_france/model/prestations/minima_sociaux/cs/ressources.py
  setup.py
  tests/formulas/cs/ressources.yaml
Labels: kind:evolution

#1410 Corrige l'application de l'abattement sur dividendes
  CHANGELOG.md
  openfisca_france/model/prelevements_obligatoires/impot_revenu/ir.py
  setup.py
  tests/calculateur_impots/yaml/abat_dividendes.yaml
Labels: kind:evolution
