Repository openfisca/openfisca-france, pull requests merged in 2021-03, with the labels that each got.

#1486 Ajoute l'éligibilité au prêt pour la formation au permis de conduire
  CHANGELOG.md
  openfisca_france/model/prestations/transport.py
  openfisca_france/parameters/prestations/transport/pret_formation_permis.yaml
  setup.py
  tests/formulas/pret_formation_permis.yaml
Labels: aides-jeunes

#1495 Force la réinstallation du build
  CHANGELOG.md
  Makefile
  setup.py
Labels: kind:devops

#1497 Ajoute une première version de Loca-pass
  CHANGELOG.md
  openfisca_france/conf/cache_blacklist.py
  openfisca_france/model/caracteristiques_socio_demographiques/demographie.py
  openfisca_france/model/prestations/locapass.py
  openfisca_france/parameters/action_logement/locapass.yaml
  setup.py
  tests/formulas/locapass.yaml
Labels: aides-jeunes

#1489 Ajoute la garantie du prêt étudiant par l'État et corrige l'appartenance à l'EEE
  CHANGELOG.md
  openfisca_france/model/caracteristiques_socio_demographiques/demographie.py
  openfisca_france/model/prestations/garantie_pret_etudiant.py
  openfisca_france/model/prestations/minima_sociaux/asi_aspa.py
  openfisca_france/model/prestations/minima_sociaux/rsa.py
  openfisca_france/parameters/geopolitique/eee.yaml
  openfisca_france/parameters/geopolitique/index.yaml
  openfisca_france/parameters/prestations/garantie_pret_etudiant/age_max.yaml
  openfisca_france/parameters/prestations/garantie_pret_etudiant/banques_conventionnees.yaml
  openfisca_france/parameters/prestations/garantie_pret_etudiant/duree_min.yaml
  openfisca_france/parameters/prestations/garantie_pret_etudiant/duree_min_residence_continue_annees.yaml
  openfisca_france/parameters/prestations/garantie_pret_etudiant/index.yaml
  openfisca_france/parameters/prestations/garantie_pret_etudiant/montant_max.yaml
  setup.py
  tests/formulas/garantie_pret_etudiant.yaml
  tests/formulas/garantie_pret_etudiant_condition_nationalite.yaml
  tests/formulas/nationalite.yaml
  tests/formulas/rsa/rsa_condition_nationalite.yaml
Labels: aides-jeunes, kind:improvement

#1496 Supprime option d'internationalisation du setup.py
  CHANGELOG.md
  setup.py
Labels: kind:devops

#1502 Ajoute l'aide au financement du permis de conduire pour les apprentis
  CHANGELOG.md
  openfisca_france/conf/cache_blacklist.py
  openfisca_france/model/prestations/transport.py
  openfisca_france/parameters/prestations/transport/aide_financement_permis_apprenti.yaml
  setup.py
  tests/formulas/aide_financement_permis_apprenti.yaml
Labels: aides-jeunes

#1492 Ajoute l'éligibilité à l'aide mobili-jeune
  CHANGELOG.md
  openfisca_france/model/base.py
  openfisca_france/model/caracteristiques_socio_demographiques/logement.py
  openfisca_france/model/prelevements_obligatoires/prelevements_sociaux/cotisations_sociales/contrat_professionnalisation.py
  openfisca_france/model/prelevements_obligatoires/prelevements_sociaux/cotisations_sociales/travail_prive.py
  openfisca_france/model/prestations/mobili_jeune.py
  openfisca_france/parameters/prestations/mobili_jeune.yaml
  setup.py
  tests/formulas/mobili_jeune.yaml
Labels: aides-jeunes

#1503 Ajoute l'aide à l’obtention du permis de conduire automobile pour les demandeurs d’emploi
  CHANGELOG.md
  openfisca_france/conf/cache_blacklist.py
  openfisca_france/model/prestations/aide_permis_demandeur_emploi.py
  openfisca_france/parameters/allocation_retour_emploi/montant_minimum.yaml
  openfisca_france/parameters/prestations/transport/aide_permis_demandeur_emploi.yaml
  setup.py
  tests/formulas/aide_permis_demandeur_emploi.yaml
Labels: aides-jeunes
